/**
 * Banque de 500+ mots français pour la génération de mots croisés.
 * Chaque mot contient : mot, indice, difficulté (1-10), catégorie.
 * Aucune dépendance externe — tout est embarqué dans l'application.
 */

export const WORD_BANK = [
  // ─── Niveau 1-2 : Mots très courants ───────────────────────────────────────
  { word: 'CHAT',    clue: 'Animal domestique qui ronronne',          level: 1, cat: 'animaux' },
  { word: 'CHIEN',   clue: 'Meilleur ami de l\'homme',               level: 1, cat: 'animaux' },
  { word: 'MAISON',  clue: 'On y vit en famille',                    level: 1, cat: 'lieux' },
  { word: 'SOLEIL',  clue: 'Étoile de notre système',                level: 1, cat: 'nature' },
  { word: 'ARBRE',   clue: 'Végétal avec un tronc et des branches',  level: 1, cat: 'nature' },
  { word: 'LIVRE',   clue: 'On y lit des histoires',                 level: 1, cat: 'objets' },
  { word: 'TABLE',   clue: 'Meuble sur lequel on mange',             level: 1, cat: 'objets' },
  { word: 'PORTE',   clue: 'Elle s\'ouvre et se ferme',              level: 1, cat: 'objets' },
  { word: 'EAU',     clue: 'Liquide vital, H₂O',                    level: 1, cat: 'nature' },
  { word: 'PAIN',    clue: 'Aliment de base en France',              level: 1, cat: 'nourriture' },
  { word: 'LUNE',    clue: 'Satellite naturel de la Terre',          level: 1, cat: 'nature' },
  { word: 'FLEUR',   clue: 'Elle pousse dans les jardins',           level: 1, cat: 'nature' },
  { word: 'ROUGE',   clue: 'Couleur du feu et du sang',              level: 1, cat: 'couleurs' },
  { word: 'BLEU',    clue: 'Couleur du ciel et de la mer',           level: 1, cat: 'couleurs' },
  { word: 'ROSE',    clue: 'Couleur entre rouge et blanc',           level: 1, cat: 'couleurs' },
  { word: 'VERT',    clue: 'Couleur de l\'herbe',                   level: 1, cat: 'couleurs' },
  { word: 'NUIT',    clue: 'Période d\'obscurité',                   level: 1, cat: 'temps' },
  { word: 'JOUR',    clue: 'Période de lumière',                     level: 1, cat: 'temps' },
  { word: 'MOIS',    clue: 'Unité de temps : janvier, février…',    level: 1, cat: 'temps' },
  { word: 'VACHE',   clue: 'Elle nous donne du lait',               level: 1, cat: 'animaux' },
  { word: 'CHEVAL',  clue: 'Animal monté par les cavaliers',         level: 1, cat: 'animaux' },
  { word: 'LAPIN',   clue: 'Petit mammifère aux longues oreilles',   level: 1, cat: 'animaux' },
  { word: 'OISEAU',  clue: 'Animal à plumes qui vole',              level: 1, cat: 'animaux' },
  { word: 'POULE',   clue: 'Elle pond des œufs',                    level: 1, cat: 'animaux' },
  { word: 'MOUTON',  clue: 'Animal à laine',                        level: 1, cat: 'animaux' },
  { word: 'BALLE',   clue: 'Objet rond qu\'on lance',               level: 1, cat: 'sport' },
  { word: 'CORDE',   clue: 'On la saute ou on l\'escalade',         level: 1, cat: 'objets' },
  { word: 'ECOLE',   clue: 'Lieu d\'apprentissage pour enfants',    level: 1, cat: 'lieux' },
  { word: 'CLASSE',  clue: 'Salle où l\'on apprend',                level: 1, cat: 'lieux' },
  { word: 'CRAYON',  clue: 'On écrit ou dessine avec lui',          level: 1, cat: 'objets' },
  { word: 'MAIN',    clue: 'On a cinq doigts sur chacune',          level: 1, cat: 'corps' },
  { word: 'PIED',    clue: 'Il porte le corps, au bout de la jambe', level: 1, cat: 'corps' },
  { word: 'TETE',    clue: 'Partie du corps qui pense',             level: 1, cat: 'corps' },
  { word: 'BRAS',    clue: 'Membre entre l\'épaule et la main',     level: 1, cat: 'corps' },
  { word: 'DOS',     clue: 'Partie arrière du corps',               level: 1, cat: 'corps' },
  { word: 'NEZ',     clue: 'Organe de l\'odorat',                   level: 1, cat: 'corps' },
  { word: 'OEIL',    clue: 'Organe de la vue',                      level: 1, cat: 'corps' },
  { word: 'BOUCHE',  clue: 'On parle et mange avec elle',           level: 1, cat: 'corps' },
  { word: 'DENT',    clue: 'Elle sert à mastiquer',                 level: 1, cat: 'corps' },
  { word: 'COEUR',   clue: 'Organe qui bat dans la poitrine',       level: 1, cat: 'corps' },
  { word: 'MER',     clue: 'Vaste étendue d\'eau salée',            level: 1, cat: 'nature' },
  { word: 'CIEL',    clue: 'Au-dessus de nos têtes, bleu par beau temps', level: 1, cat: 'nature' },
  { word: 'ETOILE',  clue: 'Elle brille dans le ciel la nuit',      level: 1, cat: 'nature' },
  { word: 'HERBE',   clue: 'Plante verte des pelouses',             level: 1, cat: 'nature' },
  { word: 'FEUILLE', clue: 'Elle tombe des arbres en automne',      level: 1, cat: 'nature' },
  { word: 'BOIS',    clue: 'Matière des arbres, ou petite forêt',   level: 1, cat: 'nature' },
  { word: 'FEU',     clue: 'Il brûle et réchauffe',                 level: 1, cat: 'nature' },
  { word: 'AIR',     clue: 'On le respire',                         level: 1, cat: 'nature' },
  { word: 'LAC',     clue: 'Étendue d\'eau douce',                  level: 1, cat: 'nature' },
  { word: 'ILE',     clue: 'Terre entourée d\'eau',                 level: 1, cat: 'nature' },
  { word: 'SABLE',   clue: 'On en trouve à la plage',               level: 1, cat: 'nature' },
  { word: 'ROUTE',   clue: 'Les voitures y circulent',              level: 1, cat: 'lieux' },
  { word: 'RUE',     clue: 'Voie bordée de maisons en ville',       level: 1, cat: 'lieux' },
  { word: 'PONT',    clue: 'Il permet de traverser une rivière',    level: 1, cat: 'lieux' },
  { word: 'VILLE',   clue: 'Grande agglomération',                  level: 1, cat: 'lieux' },
  { word: 'FERME',   clue: 'Exploitation agricole avec des animaux', level: 1, cat: 'lieux' },
  { word: 'PARC',    clue: 'Jardin public',                         level: 1, cat: 'lieux' },
  { word: 'LIT',     clue: 'Meuble pour dormir',                    level: 1, cat: 'objets' },
  { word: 'BANC',    clue: 'Siège public pour plusieurs personnes', level: 1, cat: 'objets' },
  { word: 'MUR',     clue: 'Il sépare deux pièces',                 level: 1, cat: 'objets' },
  { word: 'TOIT',    clue: 'Il couvre la maison',                   level: 1, cat: 'objets' },
  { word: 'CLE',     clue: 'Elle ouvre la serrure',                 level: 1, cat: 'objets' },
  { word: 'SAC',     clue: 'On y range ses affaires',               level: 1, cat: 'objets' },
  { word: 'VERRE',   clue: 'Récipient pour boire',                  level: 1, cat: 'objets' },
  { word: 'ASSIETTE', clue: 'On y sert le repas',                   level: 1, cat: 'objets' },
  { word: 'COUTEAU', clue: 'Ustensile qui coupe',                   level: 1, cat: 'objets' },
  { word: 'CUILLERE', clue: 'Ustensile pour la soupe',              level: 1, cat: 'objets' },
  { word: 'FOURCHETTE', clue: 'Ustensile à dents pour manger',      level: 1, cat: 'objets' },
  { word: 'BOL',     clue: 'Récipient du petit déjeuner',           level: 1, cat: 'objets' },
  { word: 'SEL',     clue: 'Assaisonnement blanc venu de la mer',   level: 1, cat: 'nourriture' },
  { word: 'SUCRE',   clue: 'Il rend les aliments doux',             level: 1, cat: 'nourriture' },
  { word: 'OEUF',    clue: 'La poule le pond',                      level: 1, cat: 'nourriture' },
  { word: 'RIZ',     clue: 'Céréale de base en Asie',               level: 1, cat: 'nourriture' },
  { word: 'SOUPE',   clue: 'Plat liquide chaud',                    level: 1, cat: 'nourriture' },
  { word: 'BANANE',  clue: 'Fruit jaune allongé',                   level: 1, cat: 'nourriture' },
  { word: 'FRAISE',  clue: 'Petit fruit rouge du printemps',        level: 1, cat: 'nourriture' },
  { word: 'CERISE',  clue: 'Petit fruit rouge à noyau',             level: 1, cat: 'nourriture' },
  { word: 'POIRE',   clue: 'Fruit à pépins, cousine de la pomme',   level: 1, cat: 'nourriture' },
  { word: 'CITRON',  clue: 'Agrume jaune et acide',                 level: 1, cat: 'nourriture' },
  { word: 'MIEL',    clue: 'Les abeilles le fabriquent',            level: 1, cat: 'nourriture' },
  { word: 'BEURRE',  clue: 'Matière grasse issue du lait',          level: 1, cat: 'nourriture' },
  { word: 'JUS',     clue: 'Boisson tirée des fruits',              level: 1, cat: 'nourriture' },
  { word: 'THE',     clue: 'Boisson chaude infusée',                level: 1, cat: 'nourriture' },
  { word: 'POISSON', clue: 'Animal qui nage et respire par branchies', level: 1, cat: 'animaux' },
  { word: 'CANARD',  clue: 'Oiseau des mares qui cancane',          level: 1, cat: 'animaux' },
  { word: 'COCHON',  clue: 'Animal rose de la ferme',               level: 1, cat: 'animaux' },
  { word: 'SOURIS',  clue: 'Petit rongeur gris',                    level: 1, cat: 'animaux' },
  { word: 'ANE',     clue: 'Cousin têtu du cheval',                 level: 1, cat: 'animaux' },
  { word: 'LOUP',    clue: 'Prédateur qui hurle à la lune',         level: 2, cat: 'animaux' },
  { word: 'OURS',    clue: 'Grand animal qui hiberne',              level: 2, cat: 'animaux' },
  { word: 'RENARD',  clue: 'Animal roux et rusé',                   level: 2, cat: 'animaux' },
  { word: 'ABEILLE', clue: 'Insecte qui fait le miel',              level: 2, cat: 'animaux' },
  { word: 'FOURMI',  clue: 'Insecte travailleur en colonie',        level: 2, cat: 'animaux' },
  { word: 'MOUCHE',  clue: 'Insecte volant agaçant',                level: 2, cat: 'animaux' },
  { word: 'SERPENT', clue: 'Reptile sans pattes',                   level: 2, cat: 'animaux' },
  { word: 'TORTUE',  clue: 'Reptile à carapace, réputée lente',     level: 2, cat: 'animaux' },
  { word: 'SINGE',   clue: 'Animal agile des arbres',               level: 2, cat: 'animaux' },
  { word: 'PERE',    clue: 'Le papa de la famille',                 level: 1, cat: 'famille' },
  { word: 'MERE',    clue: 'La maman de la famille',                level: 1, cat: 'famille' },
  { word: 'FRERE',   clue: 'Garçon né des mêmes parents',           level: 1, cat: 'famille' },
  { word: 'SOEUR',   clue: 'Fille née des mêmes parents',           level: 1, cat: 'famille' },
  { word: 'BEBE',    clue: 'Tout petit enfant',                     level: 1, cat: 'famille' },
  { word: 'ENFANT',  clue: 'Jeune personne',                        level: 1, cat: 'famille' },
  { word: 'AMI',     clue: 'On partage tout avec lui',              level: 1, cat: 'famille' },
  { word: 'ROI',     clue: 'Souverain d\'un royaume',               level: 2, cat: 'divers' },
  { word: 'REINE',   clue: 'Souveraine, épouse du roi',             level: 2, cat: 'divers' },
  { word: 'FETE',    clue: 'Moment de réjouissance',                level: 1, cat: 'fetes' },
  { word: 'JEU',     clue: 'Activité pour s\'amuser',               level: 1, cat: 'loisirs' },
  { word: 'NOIR',    clue: 'Couleur de la nuit',                    level: 1, cat: 'couleurs' },
  { word: 'BLANC',   clue: 'Couleur de la neige',                   level: 1, cat: 'couleurs' },
  { word: 'JAUNE',   clue: 'Couleur du citron',                     level: 1, cat: 'couleurs' },
  { word: 'GRIS',    clue: 'Mélange de noir et de blanc',           level: 1, cat: 'couleurs' },
  { word: 'MATIN',   clue: 'Début de la journée',                   level: 1, cat: 'temps' },
  { word: 'SOIR',    clue: 'Fin de la journée',                     level: 1, cat: 'temps' },
  { word: 'HIVER',   clue: 'Saison la plus froide',                 level: 1, cat: 'temps' },
  { word: 'ANNEE',   clue: 'Douze mois',                            level: 1, cat: 'temps' },
  { word: 'SEMAINE', clue: 'Sept jours',                            level: 1, cat: 'temps' },
  { word: 'HEURE',   clue: 'Soixante minutes',                      level: 1, cat: 'temps' },
  { word: 'MINUTE',  clue: 'Soixante secondes',                     level: 1, cat: 'temps' },
  { word: 'LUNDI',   clue: 'Premier jour de la semaine',            level: 1, cat: 'temps' },
  { word: 'DIMANCHE', clue: 'Jour de repos dominical',              level: 1, cat: 'temps' },
  { word: 'CHAPEAU', clue: 'Couvre-chef',                           level: 2, cat: 'vetements' },
  { word: 'ROBE',    clue: 'Vêtement féminin d\'une pièce',         level: 2, cat: 'vetements' },
  { word: 'PANTALON', clue: 'Vêtement qui couvre les jambes',       level: 2, cat: 'vetements' },
  { word: 'CHEMISE', clue: 'Vêtement à boutons et col',             level: 2, cat: 'vetements' },
  { word: 'MANTEAU', clue: 'Vêtement chaud d\'hiver',               level: 2, cat: 'vetements' },
  { word: 'GANT',    clue: 'Il protège la main',                    level: 2, cat: 'vetements' },
  { word: 'BOTTE',   clue: 'Chaussure montante pour la pluie',      level: 2, cat: 'vetements' },
  { word: 'ECHARPE', clue: 'On l\'enroule autour du cou',           level: 2, cat: 'vetements' },

  // ─── Niveau 3-4 : Mots courants ────────────────────────────────────────────
  { word: 'JARDIN',   clue: 'Espace vert autour d\'une maison',      level: 3, cat: 'lieux' },
  { word: 'FENETRE',  clue: 'Ouverture vitrée dans un mur',          level: 3, cat: 'objets' },
  { word: 'CUISINE',  clue: 'Pièce où l\'on prépare les repas',      level: 3, cat: 'lieux' },
  { word: 'CHAMBRE',  clue: 'Pièce où l\'on dort',                   level: 3, cat: 'lieux' },
  { word: 'CHAISE',   clue: 'Meuble pour s\'asseoir',                level: 3, cat: 'objets' },
  { word: 'BOUGIE',   clue: 'Source de lumière à flamme',            level: 3, cat: 'objets' },
  { word: 'LAMPE',    clue: 'Appareil d\'éclairage électrique',      level: 3, cat: 'objets' },
  { word: 'HORLOGE',  clue: 'Instrument qui mesure le temps',        level: 3, cat: 'objets' },
  { word: 'MIROIR',   clue: 'Surface réfléchissante',                level: 3, cat: 'objets' },
  { word: 'TAPIS',    clue: 'Revêtement souple de sol',              level: 3, cat: 'objets' },
  { word: 'PLAGE',    clue: 'Bord de mer sablonneux',                level: 3, cat: 'lieux' },
  { word: 'FORET',    clue: 'Vaste étendue boisée',                  level: 3, cat: 'nature' },
  { word: 'RIVIERE',  clue: 'Cours d\'eau moins grand qu\'un fleuve', level: 3, cat: 'nature' },
  { word: 'MONTAGNE', clue: 'Relief élevé de la terre',              level: 3, cat: 'nature' },
  { word: 'NUAGE',    clue: 'Amas de vapeur d\'eau dans le ciel',    level: 3, cat: 'nature' },
  { word: 'PLUIE',    clue: 'Précipitation liquide',                 level: 3, cat: 'nature' },
  { word: 'NEIGE',    clue: 'Précipitation blanche et froide',       level: 3, cat: 'nature' },
  { word: 'VENT',     clue: 'Mouvement de l\'air',                   level: 3, cat: 'nature' },
  { word: 'PIERRE',   clue: 'Roche, matériau dur',                   level: 3, cat: 'nature' },
  { word: 'TERRE',    clue: 'Notre planète, ou le sol',              level: 3, cat: 'nature' },
  { word: 'BATEAU',   clue: 'Véhicule qui navigue sur l\'eau',       level: 3, cat: 'transports' },
  { word: 'AVION',    clue: 'Véhicule qui vole dans les airs',       level: 3, cat: 'transports' },
  { word: 'TRAIN',    clue: 'Véhicule sur rails',                    level: 3, cat: 'transports' },
  { word: 'VELO',     clue: 'Véhicule à deux roues sans moteur',     level: 3, cat: 'transports' },
  { word: 'VOITURE',  clue: 'Véhicule automobile à quatre roues',    level: 3, cat: 'transports' },
  { word: 'MUSIQUE',  clue: 'Art des sons et des rythmes',           level: 3, cat: 'arts' },
  { word: 'CHANSON',  clue: 'Composition musicale avec paroles',     level: 3, cat: 'arts' },
  { word: 'PEINTURE', clue: 'Art d\'appliquer des couleurs sur une surface', level: 3, cat: 'arts' },
  { word: 'CINEMA',   clue: 'Salle de projection de films',          level: 3, cat: 'loisirs' },
  { word: 'THEATRE',  clue: 'Lieu de représentation scénique',       level: 3, cat: 'arts' },
  { word: 'CADEAU',   clue: 'Présent offert à quelqu\'un',           level: 3, cat: 'divers' },
  { word: 'ARGENT',   clue: 'Monnaie, ou métal précieux gris',       level: 3, cat: 'divers' },
  { word: 'MARCHE',   clue: 'Promenade à pied, ou escalier',         level: 3, cat: 'divers' },
  { word: 'COURSE',   clue: 'Compétition de vitesse',                level: 3, cat: 'sport' },
  { word: 'EQUIPE',   clue: 'Groupe de personnes qui jouent ensemble', level: 3, cat: 'sport' },
  { word: 'BALLON',   clue: 'Sphère gonflée d\'air pour les sports', level: 3, cat: 'sport' },
  { word: 'MATCH',    clue: 'Rencontre sportive',                    level: 3, cat: 'sport' },
  { word: 'STADE',    clue: 'Enceinte sportive',                     level: 3, cat: 'sport' },
  { word: 'POMME',    clue: 'Fruit rond qui tombe des arbres',       level: 3, cat: 'nourriture' },
  { word: 'ORANGE',   clue: 'Fruit agrume juteux',                   level: 3, cat: 'nourriture' },
  { word: 'RAISIN',   clue: 'Fruit en grappes, sert à faire du vin', level: 3, cat: 'nourriture' },
  { word: 'TOMATE',   clue: 'Légume rouge ou fruit selon la botanique', level: 3, cat: 'nourriture' },
  { word: 'CAROTTE',  clue: 'Légume orange allongé',                 level: 3, cat: 'nourriture' },
  { word: 'FROMAGE',  clue: 'Produit laitier fermenté',              level: 3, cat: 'nourriture' },
  { word: 'GATEAU',   clue: 'Pâtisserie sucrée',                    level: 3, cat: 'nourriture' },
  { word: 'CHOCOLAT', clue: 'Confiserie brune à base de cacao',      level: 3, cat: 'nourriture' },
  { word: 'CAFE',     clue: 'Boisson chaude tirée de grains torréfiés', level: 3, cat: 'nourriture' },
  { word: 'LAIT',     clue: 'Liquide blanc produit par les mammifères', level: 3, cat: 'nourriture' },
  { word: 'ESCALIER',  clue: 'On le monte marche par marche',           level: 3, cat: 'objets' },
  { word: 'GRENIER',   clue: 'Pièce sous le toit',                      level: 3, cat: 'lieux' },
  { word: 'CAVE',      clue: 'Pièce sous la maison',                    level: 3, cat: 'lieux' },
  { word: 'BALCON',    clue: 'Terrasse en saillie d\'un immeuble',      level: 3, cat: 'lieux' },
  { word: 'GARAGE',    clue: 'Abri pour la voiture',                    level: 3, cat: 'lieux' },
  { word: 'SALON',     clue: 'Pièce de réception avec canapé',          level: 3, cat: 'lieux' },
  { word: 'CANAPE',    clue: 'Long siège confortable du salon',         level: 3, cat: 'objets' },
  { word: 'BUREAU',    clue: 'Meuble ou pièce de travail',              level: 3, cat: 'objets' },
  { word: 'ARMOIRE',   clue: 'Meuble de rangement à portes',            level: 3, cat: 'objets' },
  { word: 'TIROIR',    clue: 'Compartiment coulissant d\'un meuble',    level: 3, cat: 'objets' },
  { word: 'RIDEAU',    clue: 'Tissu devant la fenêtre',                 level: 3, cat: 'objets' },
  { word: 'COUSSIN',   clue: 'On y pose la tête sur le canapé',         level: 3, cat: 'objets' },
  { word: 'OREILLER',  clue: 'Coussin du lit',                          level: 3, cat: 'objets' },
  { word: 'COUVERTURE', clue: 'Elle tient chaud dans le lit',           level: 3, cat: 'objets' },
  { word: 'SAVON',     clue: 'Il sert à se laver',                      level: 3, cat: 'objets' },
  { word: 'BROSSE',    clue: 'Ustensile pour les cheveux ou les dents', level: 3, cat: 'objets' },
  { word: 'PEIGNE',    clue: 'Il démêle les cheveux',                   level: 3, cat: 'objets' },
  { word: 'SERVIETTE', clue: 'Elle sèche après la douche',              level: 3, cat: 'objets' },
  { word: 'DOUCHE',    clue: 'On s\'y lave debout',                     level: 3, cat: 'objets' },
  { word: 'BAIGNOIRE', clue: 'On s\'y lave allongé',                    level: 3, cat: 'objets' },
  { word: 'LAVABO',    clue: 'Vasque de la salle de bains',             level: 3, cat: 'objets' },
  { word: 'CARTABLE',  clue: 'Sac d\'écolier',                          level: 3, cat: 'objets' },
  { word: 'CAHIER',    clue: 'On y écrit les leçons',                   level: 3, cat: 'objets' },
  { word: 'STYLO',     clue: 'Instrument d\'écriture à encre',          level: 3, cat: 'objets' },
  { word: 'GOMME',     clue: 'Elle efface le crayon',                   level: 3, cat: 'objets' },
  { word: 'REGLE',     clue: 'Instrument pour tracer des traits droits', level: 3, cat: 'objets' },
  { word: 'CISEAUX',   clue: 'Ils coupent le papier',                   level: 3, cat: 'objets' },
  { word: 'COLLE',     clue: 'Elle fait adhérer le papier',             level: 3, cat: 'objets' },
  { word: 'TABLEAU',   clue: 'Le professeur y écrit',                   level: 3, cat: 'objets' },
  { word: 'LECON',     clue: 'Ce que l\'on apprend en classe',          level: 3, cat: 'ecole' },
  { word: 'DEVOIR',    clue: 'Travail à faire à la maison',             level: 3, cat: 'ecole' },
  { word: 'VACANCES',  clue: 'Période sans école',                      level: 3, cat: 'loisirs' },
  { word: 'VOYAGE',    clue: 'Déplacement vers un lieu lointain',       level: 3, cat: 'loisirs' },
  { word: 'VALISE',    clue: 'On y range ses affaires de voyage',       level: 3, cat: 'objets' },
  { word: 'BILLET',    clue: 'Titre de transport ou d\'entrée',         level: 3, cat: 'objets' },
  { word: 'HOTEL',     clue: 'On y dort en voyage',                     level: 3, cat: 'lieux' },
  { word: 'RESTAURANT', clue: 'On y sert des repas',                    level: 3, cat: 'lieux' },
  { word: 'BOUTIQUE',  clue: 'Petit magasin',                           level: 3, cat: 'lieux' },
  { word: 'MAGASIN',   clue: 'On y fait ses courses',                   level: 3, cat: 'lieux' },
  { word: 'MARIN',     clue: 'Homme qui navigue en mer',                level: 3, cat: 'metiers' },
  { word: 'PECHEUR',   clue: 'Il attrape des poissons',                 level: 3, cat: 'metiers' },
  { word: 'FERMIER',   clue: 'Il cultive la terre et élève des bêtes',  level: 3, cat: 'metiers' },
  { word: 'BOUCHER',   clue: 'Il vend de la viande',                    level: 3, cat: 'metiers' },
  { word: 'EPICIER',   clue: 'Il tient une épicerie',                   level: 3, cat: 'metiers' },
  { word: 'FACTEUR',   clue: 'Il distribue le courrier',                level: 3, cat: 'metiers' },
  { word: 'POMPIER',   clue: 'Il éteint les incendies',                 level: 3, cat: 'metiers' },
  { word: 'POLICIER',  clue: 'Il fait respecter la loi',                level: 3, cat: 'metiers' },
  { word: 'MEDECIN',   clue: 'Il soigne les malades',                   level: 3, cat: 'metiers' },
  { word: 'INFIRMIER', clue: 'Il soigne à l\'hôpital',                  level: 3, cat: 'metiers' },
  { word: 'DENTISTE',  clue: 'Il soigne les dents',                     level: 3, cat: 'metiers' },
  { word: 'COIFFEUR',  clue: 'Il coupe les cheveux',                    level: 3, cat: 'metiers' },
  { word: 'BOULANGER', clue: 'Il fabrique le pain',                     level: 3, cat: 'metiers' },
  { word: 'CUISINIER', clue: 'Il prépare les plats',                    level: 3, cat: 'metiers' },
  { word: 'JARDINIER', clue: 'Il entretient les jardins',               level: 3, cat: 'metiers' },
  { word: 'MAITRE',    clue: 'Enseignant à l\'école primaire',          level: 3, cat: 'metiers' },
  { word: 'CAMION',    clue: 'Véhicule de transport de marchandises',   level: 3, cat: 'transports' },
  { word: 'MOTO',      clue: 'Deux-roues à moteur',                     level: 3, cat: 'transports' },
  { word: 'TRACTEUR',  clue: 'Véhicule agricole',                       level: 3, cat: 'transports' },
  { word: 'FUSEE',     clue: 'Véhicule spatial',                        level: 3, cat: 'transports' },
  { word: 'METRO',     clue: 'Train souterrain des villes',             level: 3, cat: 'transports' },
  { word: 'TRAMWAY',   clue: 'Train urbain sur rails',                  level: 3, cat: 'transports' },
  { word: 'TAXI',      clue: 'Voiture avec chauffeur à la course',      level: 3, cat: 'transports' },
  { word: 'HELICOPTERE', clue: 'Aéronef à hélice sur le toit',          level: 4, cat: 'transports' },
  { word: 'NAVIRE',    clue: 'Grand bateau',                            level: 3, cat: 'transports' },
  { word: 'VOILIER',   clue: 'Bateau à voiles',                         level: 3, cat: 'transports' },
  { word: 'PHARE',     clue: 'Tour lumineuse qui guide les marins',     level: 3, cat: 'lieux' },
  { word: 'PORT',      clue: 'Abri pour les bateaux',                   level: 3, cat: 'lieux' },
  { word: 'GARE',      clue: 'Les trains s\'y arrêtent',                level: 3, cat: 'lieux' },
  { word: 'AEROPORT',  clue: 'Les avions y décollent',                  level: 3, cat: 'lieux' },
  { word: 'USINE',     clue: 'Bâtiment de production industrielle',     level: 3, cat: 'lieux' },
  { word: 'EGLISE',    clue: 'Édifice religieux chrétien',              level: 3, cat: 'lieux' },
  { word: 'CHATEAU',   clue: 'Demeure fortifiée des seigneurs',         level: 3, cat: 'lieux' },
  { word: 'TOUR',      clue: 'Construction haute et étroite',           level: 3, cat: 'lieux' },
  { word: 'MUSEE',     clue: 'On y expose des œuvres d\'art',           level: 3, cat: 'lieux' },
  { word: 'MAIRIE',    clue: 'Bâtiment de l\'administration communale', level: 3, cat: 'lieux' },
  { word: 'HOPITAL',   clue: 'On y soigne les malades',                 level: 3, cat: 'lieux' },
  { word: 'PISCINE',   clue: 'Bassin pour nager',                       level: 3, cat: 'lieux' },
  { word: 'PATINOIRE', clue: 'Piste de glace pour patiner',             level: 4, cat: 'lieux' },
  { word: 'TENNIS',    clue: 'Sport de raquette',                       level: 3, cat: 'sport' },
  { word: 'RUGBY',     clue: 'Sport au ballon ovale',                   level: 3, cat: 'sport' },
  { word: 'BASKET',    clue: 'Sport où l\'on marque des paniers',       level: 3, cat: 'sport' },
  { word: 'JUDO',      clue: 'Art martial japonais',                    level: 3, cat: 'sport' },
  { word: 'BOXE',      clue: 'Sport de combat aux poings',              level: 3, cat: 'sport' },
  { word: 'SKI',       clue: 'Glisse sur la neige',                     level: 3, cat: 'sport' },
  { word: 'VOILE',     clue: 'Sport nautique avec le vent',             level: 3, cat: 'sport' },
  { word: 'PATIN',     clue: 'Chaussure à lame pour la glace',          level: 3, cat: 'sport' },
  { word: 'RAQUETTE',  clue: 'Instrument pour frapper la balle',        level: 3, cat: 'sport' },
  { word: 'FILET',     clue: 'Il sépare le terrain de tennis',          level: 3, cat: 'sport' },
  { word: 'ARBITRE',   clue: 'Il siffle les fautes',                    level: 3, cat: 'sport' },
  { word: 'JOUEUR',    clue: 'Il participe au match',                   level: 3, cat: 'sport' },
  { word: 'VICTOIRE',  clue: 'Succès dans une compétition',             level: 3, cat: 'sport' },
  { word: 'DEFAITE',   clue: 'Contraire de la victoire',                level: 3, cat: 'sport' },
  { word: 'POULET',    clue: 'Volaille rôtie du dimanche',              level: 3, cat: 'nourriture' },
  { word: 'JAMBON',    clue: 'Charcuterie de porc',                     level: 3, cat: 'nourriture' },
  { word: 'SAUCISSE',  clue: 'Charcuterie à griller',                   level: 3, cat: 'nourriture' },
  { word: 'SALADE',    clue: 'Légume à feuilles vertes',                level: 3, cat: 'nourriture' },
  { word: 'OIGNON',    clue: 'Légume qui fait pleurer',                 level: 3, cat: 'nourriture' },
  { word: 'POIVRE',    clue: 'Épice qui pique, compagnon du sel',       level: 3, cat: 'nourriture' },
  { word: 'MOUTARDE',  clue: 'Condiment fort de Dijon',                 level: 3, cat: 'nourriture' },
  { word: 'CONFITURE', clue: 'Fruits cuits au sucre, à tartiner',       level: 3, cat: 'nourriture' },
  { word: 'TARTINE',   clue: 'Tranche de pain garnie',                  level: 3, cat: 'nourriture' },
  { word: 'CREPE',     clue: 'Fine galette de la Chandeleur',           level: 3, cat: 'nourriture' },
  { word: 'GALETTE',   clue: 'On la partage à l\'Épiphanie',            level: 3, cat: 'nourriture' },
  { word: 'BONBON',    clue: 'Confiserie sucrée',                       level: 3, cat: 'nourriture' },
  { word: 'GLACE',     clue: 'Dessert très froid, ou miroir',           level: 3, cat: 'nourriture' },
  { word: 'YAOURT',    clue: 'Laitage fermenté en pot',                 level: 3, cat: 'nourriture' },
  { word: 'DESSERT',   clue: 'Douceur en fin de repas',                 level: 3, cat: 'nourriture' },
  { word: 'LEGUME',    clue: 'La carotte en est un',                    level: 3, cat: 'nourriture' },
  { word: 'FRUIT',     clue: 'La pomme en est un',                      level: 3, cat: 'nourriture' },
  { word: 'REPAS',     clue: 'Déjeuner ou dîner',                       level: 3, cat: 'nourriture' },
  { word: 'BOISSON',   clue: 'Liquide que l\'on boit',                  level: 3, cat: 'nourriture' },

  // ─── Niveau 5-6 : Mots intermédiaires ──────────────────────────────────────
  { word: 'BIBLIOTHEQUE', clue: 'Lieu de conservation et de prêt de livres', level: 5, cat: 'lieux' },
  { word: 'PHARMACIE',    clue: 'Lieu où l\'on vend des médicaments',        level: 5, cat: 'lieux' },
  { word: 'BOULANGERIE',  clue: 'Lieu où l\'on fabrique et vend du pain',    level: 5, cat: 'lieux' },
  { word: 'SUPERMARCHE',  clue: 'Grand magasin alimentaire en libre-service', level: 5, cat: 'lieux' },
  { word: 'UNIVERSITE',   clue: 'Établissement d\'enseignement supérieur',   level: 5, cat: 'lieux' },
  { word: 'TELESCOPE',    clue: 'Instrument pour observer les astres',        level: 5, cat: 'sciences' },
  { word: 'MICROSCOPE',   clue: 'Instrument pour voir l\'infiniment petit',  level: 5, cat: 'sciences' },
  { word: 'CHIMIE',       clue: 'Science de la matière et ses transformations', level: 5, cat: 'sciences' },
  { word: 'PHYSIQUE',     clue: 'Science des lois de la nature',             level: 5, cat: 'sciences' },
  { word: 'BIOLOGIE',     clue: 'Science du vivant',                         level: 5, cat: 'sciences' },
  { word: 'GEOGRAPHIE',   clue: 'Science qui étudie la surface terrestre',   level: 5, cat: 'sciences' },
  { word: 'HISTOIRE',     clue: 'Science qui étudie le passé humain',        level: 5, cat: 'sciences' },
  { word: 'PHILOSOPHIE',  clue: 'Science de la sagesse et de la réflexion',  level: 5, cat: 'sciences' },
  { word: 'PSYCHOLOGIE',  clue: 'Science qui étudie le comportement humain', level: 5, cat: 'sciences' },
  { word: 'ECONOMIE',     clue: 'Science de la production et des échanges',  level: 5, cat: 'sciences' },
  { word: 'ELEPHANT',     clue: 'Plus grand mammifère terrestre',            level: 5, cat: 'animaux' },
  { word: 'GIRAFE',       clue: 'Animal au cou très long',                   level: 5, cat: 'animaux' },
  { word: 'TIGRE',        clue: 'Félin rayé d\'Asie',                       level: 5, cat: 'animaux' },
  { word: 'LION',         clue: 'Roi des animaux, félin africain',           level: 5, cat: 'animaux' },
  { word: 'REQUIN',       clue: 'Poisson prédateur des mers',                level: 5, cat: 'animaux' },
  { word: 'DAUPHIN',      clue: 'Mammifère marin intelligent et joueur',     level: 5, cat: 'animaux' },
  { word: 'BALEINE',      clue: 'Plus grand mammifère marin',               level: 5, cat: 'animaux' },
  { word: 'PAPILLON',     clue: 'Insecte aux ailes colorées',               level: 5, cat: 'animaux' },
  { word: 'ARAIGNEE',     clue: 'Arachnide tisseuse de toiles',             level: 5, cat: 'animaux' },
  { word: 'CROCODILE',    clue: 'Grand reptile des marais tropicaux',        level: 5, cat: 'animaux' },
  { word: 'FOOTBALL',     clue: 'Sport collectif avec un ballon rond',       level: 5, cat: 'sport' },
  { word: 'NATATION',     clue: 'Sport aquatique',                          level: 5, cat: 'sport' },
  { word: 'CYCLISME',     clue: 'Sport pratiqué sur un vélo',               level: 5, cat: 'sport' },
  { word: 'ATHLETISME',   clue: 'Ensemble des sports de course et de saut', level: 5, cat: 'sport' },
  { word: 'ESCALADE',     clue: 'Sport consistant à grimper',               level: 5, cat: 'sport' },
  { word: 'GUITARE',      clue: 'Instrument à cordes que l\'on gratte',     level: 5, cat: 'arts' },
  { word: 'VIOLON',       clue: 'Instrument à cordes et archet',            level: 5, cat: 'arts' },
  { word: 'PIANO',        clue: 'Instrument à clavier à 88 touches',        level: 5, cat: 'arts' },
  { word: 'TROMPETTE',    clue: 'Instrument à vent en cuivre',              level: 5, cat: 'arts' },
  { word: 'SCULPTURE',    clue: 'Art de créer des formes en volume',        level: 5, cat: 'arts' },
  { word: 'ARCHITECTURE', clue: 'Art de concevoir et construire des édifices', level: 5, cat: 'arts' },
  { word: 'PHOTOGRAPHIE', clue: 'Art de capturer des images par la lumière', level: 5, cat: 'arts' },
  { word: 'PRINTEMPS',    clue: 'Saison entre hiver et été',               level: 5, cat: 'temps' },
  { word: 'AUTOMNE',      clue: 'Saison entre été et hiver',               level: 5, cat: 'temps' },
  { word: 'NOEL',         clue: 'Fête du 25 décembre',                      level: 5, cat: 'fetes' },
  { word: 'ORDINATEUR',   clue: 'Machine de traitement de l\'information',  level: 5, cat: 'technologie' },
  { word: 'CLAVIER',      clue: 'On y tape des textes',                     level: 5, cat: 'technologie' },
  { word: 'ECRAN',        clue: 'Surface d\'affichage',                     level: 5, cat: 'technologie' },
  { word: 'INTERNET',     clue: 'Réseau mondial d\'information',            level: 5, cat: 'technologie' },
  { word: 'LOGICIEL',     clue: 'Programme informatique',                   level: 5, cat: 'technologie' },
  { word: 'ROBOT',        clue: 'Machine automatisée',                      level: 5, cat: 'technologie' },
  { word: 'SATELLITE',    clue: 'Engin en orbite autour de la Terre',       level: 5, cat: 'technologie' },
  { word: 'ENERGIE',      clue: 'Capacité à produire un travail',           level: 5, cat: 'sciences' },
  { word: 'ELECTRICITE',  clue: 'Énergie qui alimente les lampes',          level: 5, cat: 'sciences' },
  { word: 'BATTERIE',     clue: 'Réserve d\'énergie, ou instrument de percussion', level: 5, cat: 'technologie' },
  { word: 'MOTEUR',       clue: 'Il fait avancer les véhicules',            level: 5, cat: 'technologie' },
  { word: 'MACHINE',      clue: 'Appareil qui effectue un travail',         level: 5, cat: 'technologie' },
  { word: 'OUTIL',        clue: 'Le marteau en est un',                     level: 5, cat: 'objets' },
  { word: 'MARTEAU',      clue: 'Outil pour planter les clous',             level: 5, cat: 'objets' },
  { word: 'TOURNEVIS',    clue: 'Outil pour visser',                        level: 5, cat: 'objets' },
  { word: 'PINCE',        clue: 'Outil pour saisir',                        level: 5, cat: 'objets' },
  { word: 'SCIE',         clue: 'Outil pour couper le bois',                level: 5, cat: 'objets' },
  { word: 'PERCEUSE',     clue: 'Outil électrique qui fait des trous',      level: 5, cat: 'objets' },
  { word: 'ECHELLE',      clue: 'On y grimpe barreau par barreau',          level: 5, cat: 'objets' },
  { word: 'BROUETTE',     clue: 'Petit véhicule de jardin à une roue',      level: 5, cat: 'objets' },
  { word: 'PELLE',        clue: 'Outil pour creuser',                       level: 5, cat: 'objets' },
  { word: 'RATEAU',       clue: 'Outil pour ramasser les feuilles',         level: 5, cat: 'objets' },
  { word: 'ARROSOIR',     clue: 'Récipient pour arroser les plantes',       level: 5, cat: 'objets' },
  { word: 'GRAINE',       clue: 'On la sème pour faire pousser',            level: 5, cat: 'nature' },
  { word: 'RACINE',       clue: 'Partie souterraine de la plante',          level: 5, cat: 'nature' },
  { word: 'TIGE',         clue: 'Elle porte la fleur',                      level: 5, cat: 'nature' },
  { word: 'PETALE',       clue: 'Élément coloré de la fleur',               level: 5, cat: 'nature' },
  { word: 'POLLEN',       clue: 'Poudre fécondante des fleurs',             level: 5, cat: 'nature' },
  { word: 'RECOLTE',      clue: 'Ramassage des produits agricoles',         level: 5, cat: 'nature' },
  { word: 'MOISSON',      clue: 'Récolte des céréales',                     level: 5, cat: 'nature' },
  { word: 'VIGNE',        clue: 'Plante qui donne le raisin',               level: 5, cat: 'nature' },
  { word: 'VERGER',       clue: 'Terrain planté d\'arbres fruitiers',       level: 5, cat: 'nature' },
  { word: 'PRAIRIE',      clue: 'Étendue d\'herbe pour les troupeaux',      level: 5, cat: 'nature' },
  { word: 'DESERT',       clue: 'Région aride presque sans pluie',          level: 5, cat: 'geographie' },
  { word: 'OASIS',        clue: 'Point d\'eau dans le désert',              level: 5, cat: 'geographie' },
  { word: 'SAVANE',       clue: 'Prairie tropicale des lions',              level: 5, cat: 'geographie' },
  { word: 'JUNGLE',       clue: 'Forêt tropicale dense',                    level: 5, cat: 'geographie' },
  { word: 'CLIMAT',       clue: 'Temps qu\'il fait sur une longue période', level: 5, cat: 'geographie' },
  { word: 'TEMPETE',      clue: 'Vent violent accompagné de pluie',         level: 5, cat: 'nature' },
  { word: 'ORAGE',        clue: 'Tonnerre et éclairs',                      level: 5, cat: 'nature' },
  { word: 'ECLAIR',       clue: 'Lumière brusque de l\'orage',              level: 5, cat: 'nature' },
  { word: 'TONNERRE',     clue: 'Bruit qui suit l\'éclair',                 level: 5, cat: 'nature' },
  { word: 'BROUILLARD',   clue: 'Nuage au ras du sol',                      level: 5, cat: 'nature' },
  { word: 'ROSEE',        clue: 'Gouttelettes du matin sur l\'herbe',       level: 5, cat: 'nature' },
  { word: 'GRELE',        clue: 'Précipitation de glaçons',                 level: 5, cat: 'nature' },
  { word: 'CANICULE',     clue: 'Période de très forte chaleur',            level: 6, cat: 'nature' },
  { word: 'SECHERESSE',   clue: 'Longue période sans pluie',                level: 6, cat: 'nature' },
  { word: 'INONDATION',   clue: 'Débordement des eaux',                     level: 6, cat: 'nature' },
  { word: 'AVALANCHE',    clue: 'Masse de neige qui dévale la pente',       level: 6, cat: 'nature' },
  { word: 'GLACIER',      clue: 'Fleuve de glace en montagne',              level: 5, cat: 'geographie' },
  { word: 'SOMMET',       clue: 'Point le plus haut d\'une montagne',       level: 5, cat: 'geographie' },
  { word: 'VALLEE',       clue: 'Dépression entre deux montagnes',          level: 5, cat: 'geographie' },
  { word: 'COLLINE',      clue: 'Petite élévation de terrain',              level: 5, cat: 'geographie' },
  { word: 'FALAISE',      clue: 'Paroi rocheuse abrupte au bord de mer',    level: 5, cat: 'geographie' },
  { word: 'GROTTE',       clue: 'Cavité naturelle dans la roche',           level: 5, cat: 'geographie' },
  { word: 'CASCADE',      clue: 'Chute d\'eau',                             level: 5, cat: 'geographie' },
  { word: 'SOURCE',       clue: 'L\'eau y jaillit du sol',                  level: 5, cat: 'geographie' },
  { word: 'FLEUVE',       clue: 'Grand cours d\'eau qui rejoint la mer',    level: 5, cat: 'geographie' },
  { word: 'CANAL',        clue: 'Voie d\'eau artificielle',                 level: 5, cat: 'geographie' },
  { word: 'BARRAGE',      clue: 'Ouvrage qui retient l\'eau',               level: 5, cat: 'geographie' },
  { word: 'HORIZON',      clue: 'Ligne où le ciel touche la terre',         level: 5, cat: 'geographie' },
  { word: 'BOUSSOLE',     clue: 'Instrument qui indique le nord',           level: 5, cat: 'objets' },
  { word: 'CARTE',        clue: 'Représentation d\'un territoire',          level: 5, cat: 'geographie' },
  { word: 'PLANETE',      clue: 'La Terre en est une',                      level: 5, cat: 'astronomie' },
  { word: 'ORBITE',       clue: 'Trajectoire autour d\'un astre',           level: 6, cat: 'astronomie' },
  { word: 'GRAVITE',      clue: 'Force qui nous retient au sol',            level: 6, cat: 'sciences' },
  { word: 'OXYGENE',      clue: 'Gaz indispensable à la respiration',       level: 5, cat: 'sciences' },
  { word: 'CARBONE',      clue: 'Élément chimique du charbon',              level: 6, cat: 'sciences' },
  { word: 'HYDROGENE',    clue: 'Élément chimique le plus léger',           level: 6, cat: 'sciences' },
  { word: 'METAL',        clue: 'Le fer en est un',                         level: 5, cat: 'sciences' },
  { word: 'CUIVRE',       clue: 'Métal rougeâtre bon conducteur',           level: 6, cat: 'sciences' },
  { word: 'PLOMB',        clue: 'Métal gris très lourd',                    level: 6, cat: 'sciences' },
  { word: 'ACIER',        clue: 'Alliage de fer et de carbone',             level: 6, cat: 'sciences' },
  { word: 'PLASTIQUE',    clue: 'Matière synthétique moderne',              level: 5, cat: 'sciences' },
  { word: 'COTON',        clue: 'Fibre textile végétale',                   level: 5, cat: 'divers' },
  { word: 'LAINE',        clue: 'Fibre textile du mouton',                  level: 5, cat: 'divers' },
  { word: 'CUIR',         clue: 'Matière issue de la peau animale',         level: 5, cat: 'divers' },
  { word: 'SOIE',         clue: 'Tissu précieux produit par un ver',        level: 5, cat: 'divers' },
  { word: 'ORCHESTRE',    clue: 'Grand ensemble de musiciens',              level: 5, cat: 'arts' },
  { word: 'CONCERT',      clue: 'Spectacle musical',                        level: 5, cat: 'arts' },
  { word: 'OPERA',        clue: 'Théâtre lyrique chanté',                   level: 6, cat: 'arts' },
  { word: 'BALLET',       clue: 'Danse classique de scène',                 level: 6, cat: 'arts' },
  { word: 'POESIE',       clue: 'Art des vers et des rimes',                level: 5, cat: 'arts' },
  { word: 'ROMAN',        clue: 'Long récit de fiction',                    level: 5, cat: 'arts' },
  { word: 'CONTE',        clue: 'Récit merveilleux pour enfants',           level: 5, cat: 'arts' },
  { word: 'LEGENDE',      clue: 'Récit traditionnel à la frontière du réel', level: 5, cat: 'arts' },
  { word: 'AUTEUR',       clue: 'Il écrit des livres',                      level: 5, cat: 'metiers' },
  { word: 'POETE',        clue: 'Il compose des vers',                      level: 5, cat: 'metiers' },
  { word: 'PEINTRE',      clue: 'Il travaille au pinceau',                  level: 5, cat: 'metiers' },
  { word: 'MUSICIEN',     clue: 'Il joue d\'un instrument',                 level: 5, cat: 'metiers' },
  { word: 'COMEDIEN',     clue: 'Il joue au théâtre',                       level: 5, cat: 'metiers' },
  { word: 'CHANTEUR',     clue: 'Il interprète des chansons',               level: 5, cat: 'metiers' },
  { word: 'DANSEUSE',     clue: 'Elle évolue sur scène en rythme',          level: 5, cat: 'metiers' },

  // ─── Niveau 7-8 : Mots avancés ─────────────────────────────────────────────
  { word: 'ARCHIPEL',     clue: 'Ensemble d\'îles dans une mer',           level: 7, cat: 'geographie' },
  { word: 'PENINSULE',    clue: 'Grande presqu\'île',                      level: 7, cat: 'geographie' },
  { word: 'FJORD',        clue: 'Bras de mer encaissé d\'origine glaciaire', level: 7, cat: 'geographie' },
  { word: 'VOLCAN',       clue: 'Montagne crachant du feu et de la lave',  level: 7, cat: 'geographie' },
  { word: 'SEISME',       clue: 'Tremblement de terre',                    level: 7, cat: 'geographie' },
  { word: 'TSUNAMI',      clue: 'Vague géante causée par un séisme',       level: 7, cat: 'geographie' },
  { word: 'ECLIPSE',      clue: 'Occultation d\'un astre par un autre',    level: 7, cat: 'astronomie' },
  { word: 'COMETE',       clue: 'Corps céleste à longue traîne lumineuse', level: 7, cat: 'astronomie' },
  { word: 'GALAXIE',      clue: 'Système de milliards d\'étoiles',         level: 7, cat: 'astronomie' },
  { word: 'NEBULEUSE',    clue: 'Nuage de gaz et poussières interstellaires', level: 7, cat: 'astronomie' },
  { word: 'PHOTON',       clue: 'Particule élémentaire de lumière',        level: 7, cat: 'physique' },
  { word: 'ELECTRON',     clue: 'Particule chargée négativement',          level: 7, cat: 'physique' },
  { word: 'PROTON',       clue: 'Particule du noyau atomique chargée +',   level: 7, cat: 'physique' },
  { word: 'ATOME',        clue: 'Plus petite unité d\'un élément chimique', level: 7, cat: 'physique' },
  { word: 'MOLECULE',     clue: 'Ensemble d\'atomes liés chimiquement',    level: 7, cat: 'physique' },
  { word: 'SYMBIOSE',     clue: 'Association bénéfique de deux espèces',   level: 7, cat: 'biologie' },
  { word: 'CHLOROPHYLLE', clue: 'Pigment vert des plantes',                level: 7, cat: 'biologie' },
  { word: 'CHROMOSOME',   clue: 'Structure portant l\'ADN dans la cellule', level: 7, cat: 'biologie' },
  { word: 'MEMBRANE',     clue: 'Fine couche qui entoure une cellule',     level: 7, cat: 'biologie' },
  { word: 'EVAPORATION',  clue: 'Passage de l\'état liquide à gazeux',     level: 7, cat: 'physique' },
  { word: 'CONDENSATION', clue: 'Passage de l\'état gazeux à liquide',     level: 7, cat: 'physique' },
  { word: 'COMBUSTION',   clue: 'Réaction chimique produisant chaleur et lumière', level: 7, cat: 'chimie' },
  { word: 'CATALYSE',     clue: 'Accélération d\'une réaction par un tiers', level: 7, cat: 'chimie' },
  { word: 'OXYDATION',    clue: 'Réaction avec l\'oxygène, cause la rouille', level: 7, cat: 'chimie' },
  { word: 'PALINDROME',   clue: 'Mot se lisant identiquement dans les deux sens', level: 7, cat: 'langue' },
  { word: 'SYNONYME',     clue: 'Mot de sens identique à un autre',        level: 7, cat: 'langue' },
  { word: 'ANTONYME',     clue: 'Mot de sens contraire à un autre',        level: 7, cat: 'langue' },
  { word: 'METAPHORE',    clue: 'Figure de style par comparaison implicite', level: 7, cat: 'langue' },
  { word: 'OXYMORE',      clue: 'Alliance de termes contradictoires',       level: 7, cat: 'langue' },
  { word: 'ISTHME',       clue: 'Étroite bande de terre entre deux mers',   level: 7, cat: 'geographie' },
  { word: 'DELTA',        clue: 'Embouchure d\'un fleuve en plusieurs bras', level: 7, cat: 'geographie' },
  { word: 'ESTUAIRE',     clue: 'Embouchure où la mer remonte le fleuve',   level: 7, cat: 'geographie' },
  { word: 'CANYON',       clue: 'Gorge profonde creusée par un cours d\'eau', level: 7, cat: 'geographie' },
  { word: 'GEYSER',       clue: 'Source chaude jaillissante',               level: 7, cat: 'geographie' },
  { word: 'BANQUISE',     clue: 'Étendue de glace flottante des pôles',     level: 7, cat: 'geographie' },
  { word: 'TOUNDRA',      clue: 'Steppe froide des régions polaires',       level: 8, cat: 'geographie' },
  { word: 'TAIGA',        clue: 'Forêt de conifères du grand nord',         level: 8, cat: 'geographie' },
  { word: 'EROSION',      clue: 'Usure du relief par l\'eau et le vent',    level: 7, cat: 'geographie' },
  { word: 'SEDIMENT',     clue: 'Dépôt laissé par l\'eau',                  level: 7, cat: 'geographie' },
  { word: 'MAGMA',        clue: 'Roche en fusion sous les volcans',         level: 7, cat: 'geographie' },
  { word: 'CRATERE',      clue: 'Bouche d\'un volcan',                      level: 7, cat: 'geographie' },
  { word: 'FAILLE',       clue: 'Fracture de l\'écorce terrestre',          level: 7, cat: 'geographie' },
  { word: 'METEORITE',    clue: 'Roche céleste tombée sur Terre',           level: 7, cat: 'astronomie' },
  { word: 'ASTEROIDE',    clue: 'Petit corps rocheux du système solaire',   level: 7, cat: 'astronomie' },
  { word: 'CONSTELLATION', clue: 'Figure dessinée par les étoiles',         level: 7, cat: 'astronomie' },
  { word: 'NEUTRON',      clue: 'Particule neutre du noyau atomique',       level: 7, cat: 'physique' },
  { word: 'ISOTOPE',      clue: 'Variante d\'un élément chimique',          level: 8, cat: 'physique' },
  { word: 'PLASMA',       clue: 'Quatrième état de la matière',             level: 8, cat: 'physique' },
  { word: 'FREQUENCE',    clue: 'Nombre d\'oscillations par seconde',       level: 7, cat: 'physique' },
  { word: 'AMPLITUDE',    clue: 'Hauteur maximale d\'une onde',             level: 8, cat: 'physique' },
  { word: 'INERTIE',      clue: 'Résistance d\'un corps au changement de mouvement', level: 8, cat: 'physique' },
  { word: 'PENDULE',      clue: 'Masse oscillant au bout d\'un fil',        level: 7, cat: 'physique' },
  { word: 'PRISME',       clue: 'Solide qui décompose la lumière',          level: 7, cat: 'physique' },
  { word: 'SPECTRE',      clue: 'Ensemble des couleurs de la lumière, ou fantôme', level: 7, cat: 'physique' },
  { word: 'LENTILLE',     clue: 'Verre optique, ou légumineuse',            level: 7, cat: 'physique' },
  { word: 'LASER',        clue: 'Faisceau de lumière concentrée',           level: 7, cat: 'physique' },
  { word: 'ENZYME',       clue: 'Protéine qui accélère les réactions du vivant', level: 8, cat: 'biologie' },
  { word: 'NEURONE',      clue: 'Cellule du système nerveux',               level: 7, cat: 'biologie' },
  { word: 'BACTERIE',     clue: 'Micro-organisme unicellulaire',            level: 7, cat: 'biologie' },
  { word: 'VIRUS',        clue: 'Agent infectieux microscopique',           level: 7, cat: 'biologie' },
  { word: 'VACCIN',       clue: 'Préparation qui immunise contre une maladie', level: 7, cat: 'biologie' },
  { word: 'ANTIDOTE',     clue: 'Remède contre un poison',                  level: 7, cat: 'biologie' },
  { word: 'GENETIQUE',    clue: 'Science de l\'hérédité',                   level: 8, cat: 'biologie' },
  { word: 'MUTATION',     clue: 'Modification du patrimoine génétique',     level: 8, cat: 'biologie' },
  { word: 'ECOSYSTEME',   clue: 'Milieu de vie et ses espèces en interaction', level: 8, cat: 'biologie' },
  { word: 'PHOTOSYNTHESE', clue: 'Fabrication de matière par les plantes grâce à la lumière', level: 8, cat: 'biologie' },
  { word: 'METAMORPHOSE', clue: 'Transformation de la chenille en papillon', level: 7, cat: 'biologie' },
  { word: 'HIBERNATION',  clue: 'Long sommeil hivernal de certains animaux', level: 7, cat: 'biologie' },
  { word: 'MIGRATION',    clue: 'Grand voyage saisonnier des oiseaux',      level: 7, cat: 'biologie' },
  { word: 'CAMOUFLAGE',   clue: 'Art de se fondre dans le décor',           level: 7, cat: 'biologie' },
  { word: 'PREDATEUR',    clue: 'Animal qui chasse d\'autres animaux',      level: 7, cat: 'biologie' },
  { word: 'PARASITE',     clue: 'Organisme vivant aux dépens d\'un autre',  level: 7, cat: 'biologie' },
  { word: 'ALLITERATION', clue: 'Répétition d\'une même consonne',          level: 8, cat: 'langue' },
  { word: 'HYPERBOLE',    clue: 'Figure de style par exagération',          level: 8, cat: 'langue' },
  { word: 'EUPHEMISME',   clue: 'Adoucissement d\'une expression',          level: 8, cat: 'langue' },
  { word: 'PERIPHRASE',   clue: 'Expression remplaçant un mot unique',      level: 8, cat: 'langue' },
  { word: 'ANAGRAMME',    clue: 'Mot formé des lettres d\'un autre',        level: 7, cat: 'langue' },
  { word: 'ETYMOLOGIE',   clue: 'Origine et histoire des mots',             level: 8, cat: 'langue' },
  { word: 'NEOLOGISME',   clue: 'Mot nouvellement créé',                    level: 8, cat: 'langue' },
  { word: 'ARCHAISME',    clue: 'Mot ou tournure vieillie',                 level: 8, cat: 'langue' },

  // ─── Niveau 9-10 : Mots experts ────────────────────────────────────────────
  { word: 'BIOLUMINESCENCE', clue: 'Émission de lumière par des organismes vivants', level: 9, cat: 'biologie' },
  { word: 'TAUTOLOGIE',      clue: 'Répétition inutile d\'une même idée',            level: 9, cat: 'langue' },
  { word: 'PLEONASME',       clue: 'Répétition d\'une idée déjà exprimée',           level: 9, cat: 'langue' },
  { word: 'ANACHRONISME',    clue: 'Erreur plaçant un fait dans une époque erronée', level: 9, cat: 'histoire' },
  { word: 'ESCHATOLOGIE',    clue: 'Doctrine des fins dernières de l\'humanité',     level: 9, cat: 'philosophie' },
  { word: 'EPISTEMOLOGIE',   clue: 'Philosophie de la connaissance scientifique',    level: 9, cat: 'philosophie' },
  { word: 'HERMENEUTIQUE',   clue: 'Science de l\'interprétation des textes',       level: 9, cat: 'philosophie' },
  { word: 'DIALECTIQUE',     clue: 'Méthode de raisonnement par thèse et antithèse', level: 9, cat: 'philosophie' },
  { word: 'PHENOMENOLOGIE',  clue: 'Étude des phénomènes de la conscience',         level: 9, cat: 'philosophie' },
  { word: 'ANTHROPOMORPHISME', clue: 'Attribution de traits humains aux animaux',   level: 9, cat: 'sciences' },
  { word: 'THERMODYNAMIQUE', clue: 'Science de la chaleur et de l\'énergie',        level: 9, cat: 'physique' },
  { word: 'HYDRODYNAMIQUE',  clue: 'Étude des fluides en mouvement',                level: 9, cat: 'physique' },
  { word: 'ELECTROMAGNETISME', clue: 'Force physique unissant électricité et magnétisme', level: 9, cat: 'physique' },
  { word: 'QUASAR',          clue: 'Noyau galactique actif très lumineux',          level: 9, cat: 'astronomie' },
  { word: 'PULSAR',          clue: 'Étoile à neutrons émettant des pulsations',     level: 9, cat: 'astronomie' },
  { word: 'SUPERNOVA',       clue: 'Explosion cataclysmique d\'une étoile mourante', level: 9, cat: 'astronomie' },
  { word: 'ANTIMATIERE',     clue: 'Matière dont les particules ont charges opposées', level: 9, cat: 'physique' },
  { word: 'XENOPHOBE',       clue: 'Qui a peur ou méprise les étrangers',           level: 9, cat: 'sociologie' },
  { word: 'PHILANTHROPE',    clue: 'Personne qui aime l\'humanité et la soutient',  level: 9, cat: 'sociologie' },
  { word: 'SERENDIPITE',     clue: 'Découverte heureuse faite par hasard',          level: 9, cat: 'langue' },
  { word: 'PALIMPSESTE',     clue: 'Manuscrit effacé puis réécrit',                 level: 10, cat: 'histoire' },
  { word: 'IDIOSYNCRASIE',   clue: 'Manière d\'être propre à un individu',          level: 10, cat: 'langue' },
  { word: 'SYLLOGISME',      clue: 'Raisonnement en deux prémisses et une conclusion', level: 9, cat: 'philosophie' },
  { word: 'SOPHISME',        clue: 'Raisonnement faux à l\'apparence logique',      level: 9, cat: 'philosophie' },
  { word: 'PARADIGME',       clue: 'Modèle de pensée dominant',                     level: 9, cat: 'philosophie' },
  { word: 'HEURISTIQUE',     clue: 'Méthode de découverte par approximation',       level: 10, cat: 'philosophie' },
  { word: 'AXIOME',          clue: 'Vérité admise sans démonstration',              level: 9, cat: 'mathematiques' },
  { word: 'COROLLAIRE',      clue: 'Conséquence directe d\'un théorème',            level: 9, cat: 'mathematiques' },
  { word: 'ASYMPTOTE',       clue: 'Droite qu\'une courbe approche sans l\'atteindre', level: 9, cat: 'mathematiques' },
  { word: 'LOGARITHME',      clue: 'Fonction inverse de l\'exponentielle',          level: 9, cat: 'mathematiques' },
  { word: 'ALGORITHME',      clue: 'Suite d\'instructions pour résoudre un problème', level: 9, cat: 'mathematiques' },
  { word: 'CRYPTOGRAPHIE',   clue: 'Science des messages secrets',                  level: 9, cat: 'sciences' },
  { word: 'ENTROPIE',        clue: 'Mesure du désordre d\'un système',              level: 9, cat: 'physique' },
  { word: 'SINGULARITE',     clue: 'Point où les lois physiques s\'effondrent',     level: 10, cat: 'physique' },
  { word: 'INTERFERENCE',    clue: 'Superposition de deux ondes',                   level: 9, cat: 'physique' },
  { word: 'SUPRACONDUCTEUR', clue: 'Matériau sans résistance électrique',           level: 10, cat: 'physique' },
  { word: 'NANOTECHNOLOGIE', clue: 'Ingénierie à l\'échelle du milliardième de mètre', level: 10, cat: 'sciences' },
  { word: 'PHOTOVOLTAIQUE',  clue: 'Qui transforme la lumière en électricité',      level: 9, cat: 'sciences' },
  { word: 'EPIGENETIQUE',    clue: 'Étude des modifications de l\'expression des gènes', level: 10, cat: 'biologie' },
  { word: 'MITOCHONDRIE',    clue: 'Centrale énergétique de la cellule',            level: 9, cat: 'biologie' },
  { word: 'ONOMATOPEE',      clue: 'Mot qui imite un son',                          level: 9, cat: 'langue' },
  { word: 'APOCRYPHE',       clue: 'Texte d\'authenticité douteuse',                level: 9, cat: 'histoire' },
  { word: 'OBSOLESCENCE',    clue: 'Vieillissement programmé d\'un produit',        level: 9, cat: 'sciences' },
  { word: 'QUINTESSENCE',    clue: 'Ce qu\'il y a de plus pur et essentiel',        level: 9, cat: 'philosophie' },
  { word: 'MISANTHROPE',     clue: 'Personne qui fuit le genre humain',             level: 9, cat: 'sociologie' },
  { word: 'EPHEMERIDE',      clue: 'Calendrier dont on détache un feuillet chaque jour', level: 9, cat: 'objets' },
];

/**
 * Retourne les mots compatibles avec un niveau de difficulté donné.
 * La plage s'élargit légèrement pour avoir suffisamment de mots.
 * @param {number} difficulty - Niveau 1 à 10
 * @param {number} count - Nombre de mots souhaités
 */
export function getWordsForDifficulty(difficulty, count) {
  // Définir la plage de niveaux selon la difficulté
  let minLevel, maxLevel;
  if (difficulty <= 2) {
    minLevel = 1; maxLevel = 2;
  } else if (difficulty <= 4) {
    minLevel = 1; maxLevel = 4;
  } else if (difficulty <= 6) {
    minLevel = 3; maxLevel = 6;
  } else if (difficulty <= 8) {
    minLevel = 5; maxLevel = 8;
  } else {
    minLevel = 7; maxLevel = 10;
  }

  // Filtrer et dédupliquer
  const seen = new Set();
  const pool = WORD_BANK.filter((w) => {
    if (w.level < minLevel || w.level > maxLevel || w.word.length < 3) return false;
    if (seen.has(w.word)) return false;
    seen.add(w.word);
    return true;
  });

  // Mélanger aléatoirement (Fisher-Yates)
  const shuffled = [...pool];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }

  return shuffled.slice(0, Math.min(count, shuffled.length));
}

/**
 * Taille de grille recommandée selon la difficulté.
 */
export function getGridSize(difficulty) {
  if (difficulty <= 2) return 10;
  if (difficulty <= 4) return 11;
  if (difficulty <= 6) return 13;
  if (difficulty <= 8) return 15;
  return 15;
}

/**
 * Nombre de mots cibles selon la difficulté.
 */
export function getWordCount(difficulty) {
  if (difficulty <= 2) return 8;
  if (difficulty <= 4) return 11;
  if (difficulty <= 6) return 14;
  if (difficulty <= 8) return 18;
  return 22;
}
