/**
 * Banque de mots anglais pour la génération de mots croisés.
 * Même structure que la banque française (lib/words.js) :
 *  - Mots en MAJUSCULES, A-Z uniquement, 3 à 15 lettres
 *  - Pas de doublons
 *  - Les catégories (`cat`) réutilisent les mêmes identifiants que la banque
 *    française afin que les thèmes fonctionnent dans les deux langues.
 * Les indices sont en anglais (grilles destinées à l'apprentissage de l'anglais).
 */

export const WORD_BANK_EN = [
  // ─── Level 1-2: Very common words ────────────────────────────────────────
  { word: 'CAT',      clue: 'Pet that purrs',                          level: 1, cat: 'animaux' },
  { word: 'DOG',      clue: 'Man\'s best friend',                      level: 1, cat: 'animaux' },
  { word: 'COW',      clue: 'Farm animal that gives milk',             level: 1, cat: 'animaux' },
  { word: 'HORSE',    clue: 'Animal ridden by a jockey',               level: 1, cat: 'animaux' },
  { word: 'RABBIT',   clue: 'Small animal with long ears',             level: 1, cat: 'animaux' },
  { word: 'BIRD',     clue: 'Feathered animal that flies',             level: 1, cat: 'animaux' },
  { word: 'HEN',      clue: 'She lays eggs',                           level: 1, cat: 'animaux' },
  { word: 'SHEEP',    clue: 'Wool comes from it',                      level: 1, cat: 'animaux' },
  { word: 'PIG',      clue: 'Pink farm animal',                        level: 1, cat: 'animaux' },
  { word: 'DUCK',     clue: 'Bird that quacks',                        level: 1, cat: 'animaux' },
  { word: 'MOUSE',    clue: 'Small grey rodent',                       level: 1, cat: 'animaux' },
  { word: 'FISH',     clue: 'It lives in water',                       level: 1, cat: 'animaux' },
  { word: 'TURTLE',   clue: 'Slow reptile with a shell',               level: 1, cat: 'animaux' },
  { word: 'BEE',      clue: 'Insect that makes honey',                 level: 1, cat: 'animaux' },
  { word: 'ANT',      clue: 'Tiny hard-working insect',                level: 1, cat: 'animaux' },
  { word: 'MONKEY',   clue: 'Animal that climbs trees',                level: 1, cat: 'animaux' },
  { word: 'BEAR',     clue: 'Big animal that hibernates',              level: 1, cat: 'animaux' },
  { word: 'WOLF',     clue: 'Wild dog that howls',                     level: 1, cat: 'animaux' },
  { word: 'FOX',      clue: 'Clever red wild animal',                  level: 1, cat: 'animaux' },
  { word: 'DEER',     clue: 'Forest animal with antlers',              level: 1, cat: 'animaux' },
  { word: 'HOUSE',    clue: 'Building where a family lives',           level: 1, cat: 'lieux' },
  { word: 'SCHOOL',   clue: 'Place where children learn',              level: 1, cat: 'lieux' },
  { word: 'FARM',     clue: 'Place with fields and animals',           level: 1, cat: 'lieux' },
  { word: 'SUN',      clue: 'Star at the center of our system',        level: 1, cat: 'nature' },
  { word: 'TREE',     clue: 'Plant with a trunk and branches',         level: 1, cat: 'nature' },
  { word: 'MOON',     clue: 'Natural satellite of the Earth',          level: 1, cat: 'nature' },
  { word: 'FLOWER',   clue: 'It grows in gardens',                     level: 1, cat: 'nature' },
  { word: 'WATER',    clue: 'Vital liquid, H2O',                       level: 1, cat: 'nature' },
  { word: 'RAIN',     clue: 'Water falling from clouds',               level: 1, cat: 'nature' },
  { word: 'SNOW',     clue: 'White winter precipitation',              level: 1, cat: 'nature' },
  { word: 'WIND',     clue: 'Moving air',                              level: 1, cat: 'nature' },
  { word: 'STAR',     clue: 'It shines in the night sky',              level: 1, cat: 'nature' },
  { word: 'BOOK',     clue: 'You read stories in it',                  level: 1, cat: 'objets' },
  { word: 'TABLE',    clue: 'Furniture you eat on',                    level: 1, cat: 'objets' },
  { word: 'DOOR',     clue: 'It opens and closes',                     level: 1, cat: 'objets' },
  { word: 'PENCIL',   clue: 'You write or draw with it',               level: 1, cat: 'objets' },
  { word: 'CHAIR',    clue: 'You sit on it',                           level: 1, cat: 'objets' },
  { word: 'CLOCK',    clue: 'It tells the time',                       level: 1, cat: 'objets' },
  { word: 'RED',      clue: 'Color of fire and blood',                 level: 1, cat: 'couleurs' },
  { word: 'BLUE',     clue: 'Color of the sky and the sea',            level: 1, cat: 'couleurs' },
  { word: 'GREEN',    clue: 'Color of grass',                          level: 1, cat: 'couleurs' },
  { word: 'PINK',     clue: 'Color between red and white',             level: 1, cat: 'couleurs' },
  { word: 'BLACK',    clue: 'Darkest color',                           level: 1, cat: 'couleurs' },
  { word: 'WHITE',    clue: 'Color of snow',                           level: 1, cat: 'couleurs' },
  { word: 'NIGHT',    clue: 'Dark period of the day',                  level: 1, cat: 'temps' },
  { word: 'DAY',      clue: 'Period of light',                         level: 1, cat: 'temps' },
  { word: 'MONTH',    clue: 'January or February, for example',        level: 1, cat: 'temps' },
  { word: 'WEEK',     clue: 'Seven days',                              level: 1, cat: 'temps' },
  { word: 'YEAR',     clue: 'Twelve months',                           level: 1, cat: 'temps' },
  { word: 'HAND',     clue: 'It has five fingers',                     level: 1, cat: 'corps' },
  { word: 'FOOT',     clue: 'You walk on it',                          level: 1, cat: 'corps' },
  { word: 'HEAD',     clue: 'Body part that holds the brain',          level: 1, cat: 'corps' },
  { word: 'ARM',      clue: 'Limb between shoulder and hand',          level: 1, cat: 'corps' },
  { word: 'LEG',      clue: 'Limb used for walking',                   level: 1, cat: 'corps' },
  { word: 'FINGER',   clue: 'The hand has five of them',               level: 1, cat: 'corps' },
  { word: 'NOSE',     clue: 'Organ of smell',                          level: 1, cat: 'corps' },
  { word: 'MOUTH',    clue: 'You speak and eat with it',               level: 1, cat: 'corps' },
  { word: 'TOOTH',    clue: 'It helps you chew',                       level: 1, cat: 'corps' },
  { word: 'HEART',    clue: 'Organ that pumps blood',                  level: 1, cat: 'corps' },
  { word: 'MOTHER',   clue: 'Mom',                                     level: 1, cat: 'famille' },
  { word: 'FATHER',   clue: 'Dad',                                     level: 1, cat: 'famille' },
  { word: 'BROTHER',  clue: 'Boy born of the same parents',            level: 1, cat: 'famille' },
  { word: 'SISTER',   clue: 'Girl born of the same parents',           level: 1, cat: 'famille' },
  { word: 'BABY',     clue: 'Very young child',                        level: 1, cat: 'famille' },
  { word: 'UNCLE',    clue: 'Your parent\'s brother',                  level: 1, cat: 'famille' },
  { word: 'AUNT',     clue: 'Your parent\'s sister',                   level: 1, cat: 'famille' },
  { word: 'COUSIN',   clue: 'Your uncle\'s child',                     level: 1, cat: 'famille' },
  { word: 'BREAD',    clue: 'Baked staple food',                       level: 1, cat: 'nourriture' },
  { word: 'EGG',      clue: 'The hen lays it',                         level: 1, cat: 'nourriture' },
  { word: 'RICE',     clue: 'Staple cereal in Asia',                   level: 1, cat: 'nourriture' },
  { word: 'SALT',     clue: 'White seasoning from the sea',            level: 1, cat: 'nourriture' },
  { word: 'SUGAR',    clue: 'It makes desserts sweet',                 level: 1, cat: 'nourriture' },
  { word: 'HONEY',    clue: 'Sweet product made by bees',              level: 1, cat: 'nourriture' },
  { word: 'SOUP',     clue: 'Hot liquid dish',                         level: 1, cat: 'nourriture' },
  { word: 'APPLE',    clue: 'Red or green fruit',                      level: 1, cat: 'nourriture' },
  { word: 'PEAR',     clue: 'Drop-shaped fruit',                       level: 1, cat: 'nourriture' },
  { word: 'MILK',     clue: 'White drink from cows',                   level: 1, cat: 'nourriture' },
  { word: 'CHEESE',   clue: 'Dairy product loved by mice',             level: 1, cat: 'nourriture' },
  { word: 'CAKE',     clue: 'Sweet baked birthday treat',              level: 1, cat: 'nourriture' },
  { word: 'BALL',     clue: 'Round object you throw',                  level: 1, cat: 'sport' },
  { word: 'GAME',     clue: 'Activity played for fun',                 level: 1, cat: 'loisirs' },

  // ─── Level 3-4: Everyday vocabulary ──────────────────────────────────────
  { word: 'GARDEN',   clue: 'Where flowers and vegetables grow',       level: 3, cat: 'nature' },
  { word: 'WINTER',   clue: 'Coldest season',                          level: 3, cat: 'temps' },
  { word: 'SUMMER',   clue: 'Hottest season',                          level: 3, cat: 'temps' },
  { word: 'SPRING',   clue: 'Season when flowers bloom',               level: 3, cat: 'temps' },
  { word: 'AUTUMN',   clue: 'Season when leaves fall',                 level: 3, cat: 'temps' },
  { word: 'RIVER',    clue: 'Water flowing to the sea',                level: 3, cat: 'geographie' },
  { word: 'MOUNTAIN', clue: 'Very high natural elevation',             level: 3, cat: 'geographie' },
  { word: 'FOREST',   clue: 'Large area covered with trees',           level: 3, cat: 'nature' },
  { word: 'ISLAND',   clue: 'Land surrounded by water',                level: 3, cat: 'geographie' },
  { word: 'DESERT',   clue: 'Very dry sandy region',                   level: 3, cat: 'geographie' },
  { word: 'OCEAN',    clue: 'Vast body of salt water',                 level: 3, cat: 'geographie' },
  { word: 'BEACH',    clue: 'Sandy shore by the sea',                  level: 3, cat: 'geographie' },
  { word: 'VILLAGE',  clue: 'Small group of houses in the country',    level: 3, cat: 'geographie' },
  { word: 'CAPITAL',  clue: 'Main city of a country',                  level: 3, cat: 'geographie' },
  { word: 'COUNTRY',  clue: 'France or Canada, for example',           level: 3, cat: 'geographie' },
  { word: 'BRIDGE',   clue: 'Structure that crosses a river',          level: 3, cat: 'lieux' },
  { word: 'CASTLE',   clue: 'Fortified home of kings',                 level: 3, cat: 'lieux' },
  { word: 'LIBRARY',  clue: 'Place full of books to borrow',           level: 3, cat: 'lieux' },
  { word: 'MUSEUM',   clue: 'Place that displays works of art',        level: 3, cat: 'lieux' },
  { word: 'MARKET',   clue: 'Place to buy fresh food',                 level: 3, cat: 'lieux' },
  { word: 'CLOUD',    clue: 'White shape floating in the sky',         level: 3, cat: 'nature' },
  { word: 'STORM',    clue: 'Violent weather with wind and rain',      level: 3, cat: 'nature' },
  { word: 'RAINBOW',  clue: 'Colored arc after the rain',              level: 3, cat: 'nature' },
  { word: 'THUNDER',  clue: 'Loud noise after lightning',              level: 3, cat: 'nature' },
  { word: 'PLANET',   clue: 'Earth or Mars, for example',              level: 3, cat: 'astronomie' },
  { word: 'COMET',    clue: 'Icy body with a bright tail',             level: 3, cat: 'astronomie' },
  { word: 'ROCKET',   clue: 'Vehicle launched into space',             level: 3, cat: 'sciences' },
  { word: 'ENERGY',   clue: 'Power needed to do work',                 level: 3, cat: 'physique' },
  { word: 'MAGNET',   clue: 'It attracts iron',                        level: 3, cat: 'physique' },
  { word: 'OXYGEN',   clue: 'Gas we need to breathe',                  level: 3, cat: 'chimie' },
  { word: 'SOCCER',   clue: 'Sport played with a round ball',          level: 3, cat: 'sport' },
  { word: 'TENNIS',   clue: 'Sport played with rackets',               level: 3, cat: 'sport' },
  { word: 'SWIMMING', clue: 'Sport practiced in a pool',               level: 3, cat: 'sport' },
  { word: 'RUNNING',  clue: 'Moving fast on your feet',                level: 3, cat: 'sport' },
  { word: 'GUITAR',   clue: 'String instrument with frets',            level: 3, cat: 'arts' },
  { word: 'PIANO',    clue: 'Keyboard instrument',                     level: 3, cat: 'arts' },
  { word: 'VIOLIN',   clue: 'String instrument played with a bow',     level: 3, cat: 'arts' },
  { word: 'PAINTER',  clue: 'Artist who works with brushes',           level: 3, cat: 'metiers' },
  { word: 'DOCTOR',   clue: 'Person who treats the sick',              level: 3, cat: 'metiers' },
  { word: 'TEACHER',  clue: 'Person who gives lessons',                level: 3, cat: 'metiers' },
  { word: 'FARMER',   clue: 'Person who works the land',               level: 3, cat: 'metiers' },
  { word: 'BAKER',    clue: 'Person who makes bread',                  level: 3, cat: 'metiers' },
  { word: 'NURSE',    clue: 'Person who cares for patients',           level: 3, cat: 'metiers' },
  { word: 'PILOT',    clue: 'Person who flies planes',                 level: 3, cat: 'metiers' },
  { word: 'LAWYER',   clue: 'Person who defends you in court',         level: 3, cat: 'metiers' },
  { word: 'CARROT',   clue: 'Orange root vegetable',                   level: 3, cat: 'nourriture' },
  { word: 'TOMATO',   clue: 'Red fruit used in salads',                level: 3, cat: 'nourriture' },
  { word: 'POTATO',   clue: 'Vegetable used for fries',                level: 3, cat: 'nourriture' },
  { word: 'ONION',    clue: 'Vegetable that makes you cry',            level: 3, cat: 'nourriture' },
  { word: 'BUTTER',   clue: 'Yellow spread made from cream',           level: 3, cat: 'nourriture' },
  { word: 'PEPPER',   clue: 'Spice ground next to the salt',           level: 3, cat: 'nourriture' },
  { word: 'LEMON',    clue: 'Sour yellow citrus fruit',                level: 3, cat: 'nourriture' },
  { word: 'ORANGE',   clue: 'Citrus fruit and a color',                level: 3, cat: 'nourriture' },
  { word: 'BANANA',   clue: 'Long yellow fruit',                       level: 3, cat: 'nourriture' },
  { word: 'CHERRY',   clue: 'Small red fruit with a stone',            level: 3, cat: 'nourriture' },

  // ─── Level 5-6: Intermediate vocabulary ──────────────────────────────────
  { word: 'VOLCANO',    clue: 'Mountain that can erupt',               level: 5, cat: 'geographie' },
  { word: 'GLACIER',    clue: 'Slow-moving river of ice',              level: 5, cat: 'geographie' },
  { word: 'PENINSULA',  clue: 'Land almost surrounded by water',       level: 5, cat: 'geographie' },
  { word: 'LATITUDE',   clue: 'Angular distance from the equator',     level: 5, cat: 'geographie' },
  { word: 'EQUATOR',    clue: 'Imaginary line around the Earth',       level: 5, cat: 'geographie' },
  { word: 'CLIMATE',    clue: 'Long-term weather pattern',             level: 5, cat: 'nature' },
  { word: 'HURRICANE',  clue: 'Huge tropical storm',                   level: 5, cat: 'nature' },
  { word: 'TORNADO',    clue: 'Violent spinning column of air',        level: 5, cat: 'nature' },
  { word: 'GRAVITY',    clue: 'Force that makes apples fall',          level: 5, cat: 'physique' },
  { word: 'MOLECULE',   clue: 'Group of bonded atoms',                 level: 5, cat: 'chimie' },
  { word: 'BACTERIA',   clue: 'Microscopic single-celled organisms',   level: 5, cat: 'biologie' },
  { word: 'ELECTRON',   clue: 'Negatively charged particle',           level: 5, cat: 'physique' },
  { word: 'GALAXY',     clue: 'The Milky Way is one',                  level: 5, cat: 'astronomie' },
  { word: 'ECLIPSE',    clue: 'When the Moon hides the Sun',           level: 5, cat: 'astronomie' },
  { word: 'DOLPHIN',    clue: 'Intelligent marine mammal',             level: 5, cat: 'animaux' },
  { word: 'PENGUIN',    clue: 'Black and white bird that cannot fly',  level: 5, cat: 'animaux' },
  { word: 'LEOPARD',    clue: 'Spotted big cat',                       level: 5, cat: 'animaux' },
  { word: 'GIRAFFE',    clue: 'Tallest land animal',                   level: 5, cat: 'animaux' },
  { word: 'ELEPHANT',   clue: 'Largest land animal, with a trunk',     level: 5, cat: 'animaux' },
  { word: 'KANGAROO',   clue: 'Australian animal that jumps',          level: 5, cat: 'animaux' },
  { word: 'OCTOPUS',    clue: 'Sea animal with eight arms',            level: 5, cat: 'animaux' },
  { word: 'FALCON',     clue: 'Fast bird of prey',                     level: 5, cat: 'animaux' },
  { word: 'SALMON',     clue: 'Fish that swims upstream',              level: 5, cat: 'animaux' },
  { word: 'MARATHON',   clue: 'Race of about 42 kilometers',           level: 5, cat: 'sport' },
  { word: 'GYMNASTICS', clue: 'Sport with bars, rings and beams',      level: 5, cat: 'sport' },
  { word: 'CHAMPION',   clue: 'Winner of a competition',               level: 5, cat: 'sport' },
  { word: 'STADIUM',    clue: 'Large arena for sports events',         level: 5, cat: 'sport' },
  { word: 'SCULPTURE',  clue: 'Three-dimensional work of art',         level: 5, cat: 'arts' },
  { word: 'ORCHESTRA',  clue: 'Large group of musicians',              level: 5, cat: 'arts' },
  { word: 'THEATER',    clue: 'Place where plays are performed',       level: 5, cat: 'arts' },
  { word: 'POETRY',     clue: 'Literature written in verse',           level: 5, cat: 'langue' },
  { word: 'HARMONY',    clue: 'Pleasant combination of notes',         level: 5, cat: 'arts' },
  { word: 'NOVELIST',   clue: 'Writer of long fiction',                level: 5, cat: 'metiers' },
  { word: 'ARCHITECT',  clue: 'Person who designs buildings',          level: 5, cat: 'metiers' },
  { word: 'ENGINEER',   clue: 'Person who designs machines',           level: 5, cat: 'metiers' },
  { word: 'JOURNALIST', clue: 'Person who reports the news',           level: 5, cat: 'metiers' },
  { word: 'SURGEON',    clue: 'Doctor who operates',                   level: 5, cat: 'metiers' },
  { word: 'CINNAMON',   clue: 'Sweet brown spice',                     level: 5, cat: 'nourriture' },
  { word: 'AVOCADO',    clue: 'Green fruit used in guacamole',         level: 5, cat: 'nourriture' },
  { word: 'SPINACH',    clue: 'Leafy green loved by Popeye',           level: 5, cat: 'nourriture' },

  // ─── Level 7-8: Advanced vocabulary ──────────────────────────────────────
  { word: 'PHOTOSYNTHESIS', clue: 'How plants turn light into food',   level: 7, cat: 'biologie' },
  { word: 'CHROMOSOME',     clue: 'DNA structure carrying genes',      level: 7, cat: 'biologie' },
  { word: 'ANTIBODY',       clue: 'Protein that fights infection',     level: 7, cat: 'biologie' },
  { word: 'CATALYST',       clue: 'It speeds up a reaction',           level: 7, cat: 'chimie' },
  { word: 'NEBULA',         clue: 'Interstellar cloud of gas',         level: 7, cat: 'astronomie' },
  { word: 'QUASAR',         clue: 'Extremely bright galactic core',    level: 7, cat: 'astronomie' },
  { word: 'ARCHIPELAGO',    clue: 'Group of islands',                  level: 7, cat: 'geographie' },
  { word: 'METAMORPHOSIS',  clue: 'Caterpillar-to-butterfly change',   level: 7, cat: 'biologie' },
  { word: 'PHILOSOPHY',     clue: 'The study of wisdom',               level: 7, cat: 'philosophie' },
  { word: 'RENAISSANCE',    clue: 'Cultural rebirth after the Middle Ages', level: 7, cat: 'histoire' },
  { word: 'DEMOCRACY',      clue: 'Government by the people',          level: 7, cat: 'histoire' },
  { word: 'METAPHOR',       clue: 'Comparison without "like" or "as"', level: 7, cat: 'langue' },
  { word: 'SYMPHONY',       clue: 'Long orchestral composition',       level: 7, cat: 'arts' },
  { word: 'ASTRONOMER',     clue: 'Scientist who studies the stars',   level: 7, cat: 'metiers' },
  { word: 'CHAMELEON',      clue: 'Lizard that changes color',         level: 7, cat: 'animaux' },
  { word: 'PLATYPUS',       clue: 'Egg-laying mammal with a bill',     level: 7, cat: 'animaux' },
  { word: 'RHINOCEROS',     clue: 'Large animal with a horned nose',   level: 7, cat: 'animaux' },
  { word: 'CONSTITUTION',   clue: 'Fundamental law of a nation',       level: 7, cat: 'histoire' },
  { word: 'ECOSYSTEM',      clue: 'Community of living things',        level: 7, cat: 'biologie' },
  { word: 'PENDULUM',       clue: 'Swinging weight in old clocks',     level: 7, cat: 'physique' },

  // ─── Level 9-10: Expert vocabulary ───────────────────────────────────────
  { word: 'PALINDROME',    clue: 'Word reading the same both ways',    level: 9, cat: 'langue' },
  { word: 'HYPERBOLE',     clue: 'Deliberate exaggeration',            level: 9, cat: 'langue' },
  { word: 'OXYMORON',      clue: 'Contradiction like "deafening silence"', level: 9, cat: 'langue' },
  { word: 'IDIOSYNCRASY',  clue: 'Peculiar personal habit',            level: 9, cat: 'langue' },
  { word: 'JUXTAPOSITION', clue: 'Placing side by side for contrast',  level: 9, cat: 'arts' },
  { word: 'KALEIDOSCOPE',  clue: 'Tube of mirrors and shifting colors', level: 9, cat: 'objets' },
  { word: 'LABYRINTH',     clue: 'Maze of Greek legend',               level: 9, cat: 'histoire' },
  { word: 'EPIPHANY',      clue: 'Sudden moment of insight',           level: 9, cat: 'philosophie' },
  { word: 'PARADIGM',      clue: 'Typical model or framework',         level: 9, cat: 'philosophie' },
  { word: 'SOLILOQUY',     clue: 'Speech delivered alone on stage',    level: 9, cat: 'arts' },
  { word: 'CACOPHONY',     clue: 'Harsh mixture of sounds',            level: 9, cat: 'langue' },
  { word: 'EUPHEMISM',     clue: 'Mild word for a harsh reality',      level: 9, cat: 'langue' },
  { word: 'VERNACULAR',    clue: 'Everyday language of a region',      level: 9, cat: 'langue' },
  { word: 'APOTHEOSIS',    clue: 'Highest point of development',       level: 9, cat: 'philosophie' },
  { word: 'SERENDIPITY',   clue: 'Happy accidental discovery',         level: 9, cat: 'philosophie' },
];
