/**
 * Banque de mots français pour la génération de mots croisés.
 * Chaque mot contient : mot, indice, difficulté (1-10), catégorie.
 * Aucune dépendance externe — tout est embarqué dans l'application.
 *
 * Règles de la banque :
 *  - Mots en MAJUSCULES, sans accents ni traits d'union (A-Z uniquement)
 *  - Longueur entre 3 et 15 lettres (15 = plus grande grille générée)
 *  - Pas de doublons
 */

export const WORD_BANK = [
  // ─── Niveau 1-2 : Mots très courants ───────────────────────────────────────
  { word: 'CHAT',    clue: 'Animal domestique qui ronronne',          level: 1, cat: 'animaux' },
  { word: 'CHIEN',   clue: 'Meilleur ami de l\'homme',               level: 1, cat: 'animaux' },
  { word: 'MAISON',  clue: 'On y vit en famille',                    level: 1, cat: 'lieux' },
  { word: 'SOLEIL',  clue: 'Étoile de notre système',                level: 1, cat: 'nature' },
  { word: 'ARBRE',   clue: 'Végétal avec un tronc et des branches',  level: 1, cat: 'nature' },
  { word: 'LIVRE',   clue: 'On y lit des histoires',                 level: 1, cat: 'objets' },
  { word: 'TABLE',   clue: 'Meuble sur lequel on mange',             level: 1, cat: 'objets' },
  { word: 'PORTE',   clue: 'Elle s\'ouvre et se ferme',              level: 1, cat: 'objets' },
  { word: 'EAU',     clue: 'Liquide vital, H₂O',                    level: 1, cat: 'nature' },
  { word: 'PAIN',    clue: 'Aliment de base en France',              level: 1, cat: 'nourriture' },
  { word: 'LUNE',    clue: 'Satellite naturel de la Terre',          level: 1, cat: 'nature' },
  { word: 'FLEUR',   clue: 'Elle pousse dans les jardins',           level: 1, cat: 'nature' },
  { word: 'ROUGE',   clue: 'Couleur du feu et du sang',              level: 1, cat: 'couleurs' },
  { word: 'BLEU',    clue: 'Couleur du ciel et de la mer',           level: 1, cat: 'couleurs' },
  { word: 'ROSE',    clue: 'Couleur entre rouge et blanc',           level: 1, cat: 'couleurs' },
  { word: 'VERT',    clue: 'Couleur de l\'herbe',                   level: 1, cat: 'couleurs' },
  { word: 'NUIT',    clue: 'Période d\'obscurité',                   level: 1, cat: 'temps' },
  { word: 'JOUR',    clue: 'Période de lumière',                     level: 1, cat: 'temps' },
  { word: 'MOIS',    clue: 'Unité de temps : janvier, février…',    level: 1, cat: 'temps' },
  { word: 'VACHE',   clue: 'Elle nous donne du lait',               level: 1, cat: 'animaux' },
  { word: 'CHEVAL',  clue: 'Animal monté par les cavaliers',         level: 1, cat: 'animaux' },
  { word: 'LAPIN',   clue: 'Petit mammifère aux longues oreilles',   level: 1, cat: 'animaux' },
  { word: 'OISEAU',  clue: 'Animal à plumes qui vole',              level: 1, cat: 'animaux' },
  { word: 'POULE',   clue: 'Elle pond des œufs',                    level: 1, cat: 'animaux' },
  { word: 'MOUTON',  clue: 'Animal à laine',                        level: 1, cat: 'animaux' },
  { word: 'BALLE',   clue: 'Objet rond qu\'on lance',               level: 1, cat: 'sport' },
  { word: 'CORDE',   clue: 'On la saute ou on l\'escalade',         level: 1, cat: 'objets' },
  { word: 'ECOLE',   clue: 'Lieu d\'apprentissage pour enfants',    level: 1, cat: 'lieux' },
  { word: 'CLASSE',  clue: 'Salle où l\'on apprend',                level: 1, cat: 'lieux' },
  { word: 'CRAYON',  clue: 'On écrit ou dessine avec lui',          level: 1, cat: 'objets' },
  { word: 'COCHON',  clue: 'Animal rose de la ferme',               level: 1, cat: 'animaux' },
  { word: 'CANARD',  clue: 'Oiseau qui fait coin-coin',             level: 1, cat: 'animaux' },
  { word: 'SOURIS',  clue: 'Petit rongeur gris, ou accessoire d\'ordinateur', level: 1, cat: 'animaux' },
  { word: 'POISSON', clue: 'Animal qui vit dans l\'eau',            level: 1, cat: 'animaux' },
  { word: 'TORTUE',  clue: 'Reptile lent à carapace',               level: 1, cat: 'animaux' },
  { word: 'ABEILLE', clue: 'Insecte qui fabrique le miel',          level: 1, cat: 'animaux' },
  { word: 'FOURMI',  clue: 'Petit insecte très travailleur',        level: 1, cat: 'animaux' },
  { word: 'SINGE',   clue: 'Animal qui grimpe aux arbres et imite', level: 1, cat: 'animaux' },
  { word: 'OURS',    clue: 'Grand animal qui hiberne',              level: 1, cat: 'animaux' },
  { word: 'LOUP',    clue: 'Canidé sauvage qui hurle à la lune',    level: 1, cat: 'animaux' },
  { word: 'RENARD',  clue: 'Canidé roux réputé rusé',               level: 1, cat: 'animaux' },
  { word: 'CERF',    clue: 'Animal de la forêt aux grands bois',    level: 1, cat: 'animaux' },
  { word: 'MAIN',    clue: 'Elle a cinq doigts',                    level: 1, cat: 'corps' },
  { word: 'PIED',    clue: 'On marche dessus',                      level: 1, cat: 'corps' },
  { word: 'TETE',    clue: 'Partie du corps qui porte le cerveau',  level: 1, cat: 'corps' },
  { word: 'BRAS',    clue: 'Membre entre l\'épaule et la main',     level: 1, cat: 'corps' },
  { word: 'JAMBE',   clue: 'Membre qui sert à marcher',             level: 1, cat: 'corps' },
  { word: 'DOIGT',   clue: 'La main en compte cinq',                level: 1, cat: 'corps' },
  { word: 'NEZ',     clue: 'Organe de l\'odorat',                   level: 1, cat: 'corps' },
  { word: 'BOUCHE',  clue: 'On parle et on mange avec elle',        level: 1, cat: 'corps' },
  { word: 'DENT',    clue: 'Elle sert à mâcher',                    level: 1, cat: 'corps' },
  { word: 'COEUR',   clue: 'Organe qui pompe le sang',              level: 1, cat: 'corps' },
  { word: 'MERE',    clue: 'Maman',                                 level: 1, cat: 'famille' },
  { word: 'PERE',    clue: 'Papa',                                  level: 1, cat: 'famille' },
  { word: 'FRERE',   clue: 'Garçon né des mêmes parents',           level: 1, cat: 'famille' },
  { word: 'SOEUR',   clue: 'Fille née des mêmes parents',           level: 1, cat: 'famille' },
  { word: 'BEBE',    clue: 'Très jeune enfant',                     level: 1, cat: 'famille' },
  { word: 'ONCLE',   clue: 'Frère du père ou de la mère',           level: 1, cat: 'famille' },
  { word: 'TANTE',   clue: 'Sœur du père ou de la mère',            level: 1, cat: 'famille' },
  { word: 'COUSIN',  clue: 'Fils de l\'oncle ou de la tante',       level: 1, cat: 'famille' },
  { word: 'OEUF',    clue: 'La poule le pond',                      level: 1, cat: 'nourriture' },
  { word: 'RIZ',     clue: 'Céréale de base en Asie',               level: 1, cat: 'nourriture' },
  { word: 'SEL',     clue: 'Assaisonnement blanc de la mer',        level: 1, cat: 'nourriture' },
  { word: 'SUCRE',   clue: 'Il rend les desserts doux',             level: 1, cat: 'nourriture' },
  { word: 'MIEL',    clue: 'Produit sucré des abeilles',            level: 1, cat: 'nourriture' },
  { word: 'SOUPE',   clue: 'Plat liquide chaud de légumes',         level: 1, cat: 'nourriture' },
  { word: 'POIRE',   clue: 'Fruit jaune ou vert en forme de goutte', level: 1, cat: 'nourriture' },
  { word: 'BANANE',  clue: 'Fruit jaune allongé',                   level: 1, cat: 'nourriture' },
  { word: 'FRAISE',  clue: 'Petit fruit rouge du printemps',        level: 1, cat: 'nourriture' },
  { word: 'CERISE',  clue: 'Petit fruit rouge à noyau',             level: 1, cat: 'nourriture' },
  { word: 'CITRON',  clue: 'Agrume jaune très acide',               level: 1, cat: 'nourriture' },
  { word: 'MER',     clue: 'Grande étendue d\'eau salée',           level: 1, cat: 'nature' },
  { word: 'CIEL',    clue: 'Il est bleu au-dessus de nos têtes',    level: 1, cat: 'nature' },
  { word: 'HERBE',   clue: 'Plante verte des prairies',             level: 1, cat: 'nature' },
  { word: 'FEU',     clue: 'Il brûle et réchauffe',                 level: 1, cat: 'nature' },
  { word: 'LAC',     clue: 'Étendue d\'eau douce entourée de terre', level: 1, cat: 'nature' },
  { word: 'ETOILE',  clue: 'Point lumineux dans le ciel nocturne',  level: 1, cat: 'nature' },
  { word: 'PLANTE',  clue: 'Végétal qui pousse en pot ou en terre', level: 1, cat: 'nature' },
  { word: 'STYLO',   clue: 'On écrit à l\'encre avec lui',          level: 1, cat: 'objets' },
  { word: 'CAHIER',  clue: 'On y écrit ses leçons',                 level: 1, cat: 'objets' },
  { word: 'SAC',     clue: 'On y range ses affaires',               level: 1, cat: 'objets' },
  { word: 'CLE',     clue: 'Elle ouvre la serrure',                 level: 1, cat: 'objets' },
  { word: 'VERRE',   clue: 'Récipient pour boire',                  level: 1, cat: 'objets' },
  { word: 'LIT',     clue: 'Meuble pour dormir',                    level: 1, cat: 'objets' },
  { word: 'ROBE',    clue: 'Vêtement féminin d\'une seule pièce',   level: 1, cat: 'vetements' },
  { word: 'PULL',    clue: 'Vêtement chaud en laine',               level: 1, cat: 'vetements' },
  { word: 'JUPE',    clue: 'Vêtement qui couvre à partir de la taille', level: 1, cat: 'vetements' },
  { word: 'BOTTE',   clue: 'Chaussure montante pour la pluie',      level: 1, cat: 'vetements' },
  { word: 'GANT',    clue: 'Il protège la main du froid',           level: 1, cat: 'vetements' },
  { word: 'CHAPEAU', clue: 'Couvre-chef',                           level: 1, cat: 'vetements' },
  { word: 'BUS',     clue: 'Transport en commun urbain',            level: 1, cat: 'transports' },
  { word: 'MOTO',    clue: 'Deux-roues à moteur',                   level: 1, cat: 'transports' },
  { word: 'ROUE',    clue: 'Elle tourne sous les véhicules',        level: 1, cat: 'transports' },
  { word: 'NOIR',    clue: 'Couleur de la nuit',                    level: 1, cat: 'couleurs' },
  { word: 'BLANC',   clue: 'Couleur de la neige',                   level: 1, cat: 'couleurs' },
  { word: 'JAUNE',   clue: 'Couleur du citron et du soleil',        level: 1, cat: 'couleurs' },
  { word: 'GRIS',    clue: 'Couleur entre noir et blanc',           level: 1, cat: 'couleurs' },
  { word: 'HIVER',   clue: 'Saison la plus froide',                 level: 1, cat: 'temps' },
  { word: 'ETE',     clue: 'Saison la plus chaude',                 level: 1, cat: 'temps' },
  { word: 'ANNEE',   clue: 'Douze mois',                            level: 1, cat: 'temps' },
  { word: 'MATIN',   clue: 'Début de la journée',                   level: 1, cat: 'temps' },
  { word: 'SOIR',    clue: 'Fin de la journée',                     level: 1, cat: 'temps' },
  { word: 'MIDI',    clue: 'Milieu de la journée, 12 heures',       level: 1, cat: 'temps' },
  { word: 'JEU',     clue: 'Activité pour s\'amuser',               level: 1, cat: 'loisirs' },
  { word: 'FERME',   clue: 'Exploitation agricole avec des animaux', level: 1, cat: 'lieux' },
  { word: 'PARC',    clue: 'Espace vert public pour se promener',   level: 1, cat: 'lieux' },
  { word: 'RUE',     clue: 'Voie bordée de maisons en ville',       level: 1, cat: 'lieux' },
  { word: 'PONT',    clue: 'Il permet de traverser une rivière',    level: 1, cat: 'lieux' },

  // ─── Niveau 3-4 : Mots courants ────────────────────────────────────────────
  { word: 'JARDIN',   clue: 'Espace vert autour d\'une maison',      level: 3, cat: 'lieux' },
  { word: 'FENETRE',  clue: 'Ouverture vitrée dans un mur',          level: 3, cat: 'objets' },
  { word: 'CUISINE',  clue: 'Pièce où l\'on prépare les repas',      level: 3, cat: 'lieux' },
  { word: 'CHAMBRE',  clue: 'Pièce où l\'on dort',                   level: 3, cat: 'lieux' },
  { word: 'CHAISE',   clue: 'Meuble pour s\'asseoir',                level: 3, cat: 'objets' },
  { word: 'BOUGIE',   clue: 'Source de lumière à flamme',            level: 3, cat: 'objets' },
  { word: 'LAMPE',    clue: 'Appareil d\'éclairage électrique',      level: 3, cat: 'objets' },
  { word: 'HORLOGE',  clue: 'Instrument qui mesure le temps',        level: 3, cat: 'objets' },
  { word: 'MIROIR',   clue: 'Surface réfléchissante',                level: 3, cat: 'objets' },
  { word: 'TAPIS',    clue: 'Revêtement souple de sol',              level: 3, cat: 'objets' },
  { word: 'PLAGE',    clue: 'Bord de mer sablonneux',                level: 3, cat: 'lieux' },
  { word: 'FORET',    clue: 'Vaste étendue boisée',                  level: 3, cat: 'nature' },
  { word: 'RIVIERE',  clue: 'Cours d\'eau moins grand qu\'un fleuve', level: 3, cat: 'nature' },
  { word: 'MONTAGNE', clue: 'Relief élevé de la terre',              level: 3, cat: 'nature' },
  { word: 'NUAGE',    clue: 'Amas de vapeur d\'eau dans le ciel',    level: 3, cat: 'nature' },
  { word: 'PLUIE',    clue: 'Précipitation liquide',                 level: 3, cat: 'nature' },
  { word: 'NEIGE',    clue: 'Précipitation blanche et froide',       level: 3, cat: 'nature' },
  { word: 'VENT',     clue: 'Mouvement de l\'air',                   level: 3, cat: 'nature' },
  { word: 'PIERRE',   clue: 'Roche, matériau dur',                   level: 3, cat: 'nature' },
  { word: 'TERRE',    clue: 'Notre planète, ou le sol',              level: 3, cat: 'nature' },
  { word: 'BATEAU',   clue: 'Véhicule qui navigue sur l\'eau',       level: 3, cat: 'transports' },
  { word: 'AVION',    clue: 'Véhicule qui vole dans les airs',       level: 3, cat: 'transports' },
  { word: 'TRAIN',    clue: 'Véhicule sur rails',                    level: 3, cat: 'transports' },
  { word: 'VELO',     clue: 'Véhicule à deux roues sans moteur',     level: 3, cat: 'transports' },
  { word: 'VOITURE',  clue: 'Véhicule automobile à quatre roues',    level: 3, cat: 'transports' },
  { word: 'MUSIQUE',  clue: 'Art des sons et des rythmes',           level: 3, cat: 'arts' },
  { word: 'CHANSON',  clue: 'Composition musicale avec paroles',     level: 3, cat: 'arts' },
  { word: 'PEINTURE', clue: 'Art d\'appliquer des couleurs sur une surface', level: 3, cat: 'arts' },
  { word: 'CINEMA',   clue: 'Salle de projection de films',          level: 3, cat: 'loisirs' },
  { word: 'THEATRE',  clue: 'Lieu de représentation scénique',       level: 3, cat: 'arts' },
  { word: 'CADEAU',   clue: 'Présent offert à quelqu\'un',           level: 3, cat: 'divers' },
  { word: 'ARGENT',   clue: 'Monnaie, ou métal précieux gris',       level: 3, cat: 'divers' },
  { word: 'MARCHE',   clue: 'Promenade à pied, ou escalier',         level: 3, cat: 'divers' },
  { word: 'COURSE',   clue: 'Compétition de vitesse',                level: 3, cat: 'sport' },
  { word: 'EQUIPE',   clue: 'Groupe de personnes qui jouent ensemble', level: 3, cat: 'sport' },
  { word: 'BALLON',   clue: 'Sphère gonflée d\'air pour les sports', level: 3, cat: 'sport' },
  { word: 'MATCH',    clue: 'Rencontre sportive',                    level: 3, cat: 'sport' },
  { word: 'STADE',    clue: 'Enceinte sportive',                     level: 3, cat: 'sport' },
  { word: 'POMME',    clue: 'Fruit rond qui tombe des arbres',       level: 3, cat: 'nourriture' },
  { word: 'ORANGE',   clue: 'Fruit agrume juteux',                   level: 3, cat: 'nourriture' },
  { word: 'RAISIN',   clue: 'Fruit en grappes, sert à faire du vin', level: 3, cat: 'nourriture' },
  { word: 'TOMATE',   clue: 'Légume rouge ou fruit selon la botanique', level: 3, cat: 'nourriture' },
  { word: 'CAROTTE',  clue: 'Légume orange allongé',                 level: 3, cat: 'nourriture' },
  { word: 'FROMAGE',  clue: 'Produit laitier fermenté',              level: 3, cat: 'nourriture' },
  { word: 'GATEAU',   clue: 'Pâtisserie sucrée',                    level: 3, cat: 'nourriture' },
  { word: 'CHOCOLAT', clue: 'Confiserie brune à base de cacao',      level: 3, cat: 'nourriture' },
  { word: 'CAFE',     clue: 'Boisson chaude tirée de grains torréfiés', level: 3, cat: 'nourriture' },
  { word: 'LAIT',     clue: 'Liquide blanc produit par les mammifères', level: 3, cat: 'nourriture' },
  { word: 'MEDECIN',  clue: 'Il soigne les malades',                 level: 3, cat: 'metiers' },
  { word: 'BOULANGER', clue: 'Il fabrique le pain',                  level: 3, cat: 'metiers' },
  { word: 'FERMIER',  clue: 'Il cultive la terre et élève des animaux', level: 3, cat: 'metiers' },
  { word: 'POMPIER',  clue: 'Il éteint les incendies',               level: 3, cat: 'metiers' },
  { word: 'FACTEUR',  clue: 'Il distribue le courrier',              level: 3, cat: 'metiers' },
  { word: 'COIFFEUR', clue: 'Il coupe les cheveux',                  level: 3, cat: 'metiers' },
  { word: 'CUISINIER', clue: 'Il prépare les plats au restaurant',   level: 3, cat: 'metiers' },
  { word: 'PILOTE',   clue: 'Il conduit un avion',                   level: 3, cat: 'metiers' },
  { word: 'INFIRMIER', clue: 'Il soigne les patients à l\'hôpital',  level: 3, cat: 'metiers' },
  { word: 'POLICIER', clue: 'Il fait respecter la loi',              level: 3, cat: 'metiers' },
  { word: 'JARDINIER', clue: 'Il entretient les espaces verts',      level: 3, cat: 'metiers' },
  { word: 'BOUCHER',  clue: 'Il vend de la viande',                  level: 3, cat: 'metiers' },
  { word: 'DENTISTE', clue: 'Il soigne les dents',                   level: 3, cat: 'metiers' },
  { word: 'AVOCAT',   clue: 'Il défend ses clients au tribunal, ou fruit vert', level: 3, cat: 'metiers' },
  { word: 'PAYS',     clue: 'Territoire d\'une nation',              level: 3, cat: 'geographie' },
  { word: 'VILLE',    clue: 'Grande agglomération urbaine',          level: 3, cat: 'geographie' },
  { word: 'FLEUVE',   clue: 'Grand cours d\'eau qui se jette dans la mer', level: 3, cat: 'geographie' },
  { word: 'DESERT',   clue: 'Région aride presque sans pluie',       level: 3, cat: 'geographie' },
  { word: 'COLLINE',  clue: 'Petite élévation de terrain arrondie',  level: 3, cat: 'geographie' },
  { word: 'VALLEE',   clue: 'Dépression entre deux montagnes',       level: 3, cat: 'geographie' },
  { word: 'OCEAN',    clue: 'Immense étendue d\'eau salée',          level: 3, cat: 'geographie' },
  { word: 'CARTE',    clue: 'Représentation d\'un territoire',       level: 3, cat: 'geographie' },
  { word: 'NORD',     clue: 'Direction de la boussole opposée au sud', level: 3, cat: 'geographie' },
  { word: 'SUD',      clue: 'Point cardinal opposé au nord',         level: 3, cat: 'geographie' },
  { word: 'OUEST',    clue: 'Point cardinal du soleil couchant',     level: 3, cat: 'geographie' },
  { word: 'CAPITALE', clue: 'Ville principale d\'un pays',           level: 3, cat: 'geographie' },
  { word: 'COQ',      clue: 'Mâle de la poule, emblème français',    level: 3, cat: 'animaux' },
  { word: 'ANE',      clue: 'Équidé aux longues oreilles',           level: 3, cat: 'animaux' },
  { word: 'CHEVRE',   clue: 'Elle donne du lait pour le fromage du même nom', level: 3, cat: 'animaux' },
  { word: 'AIGLE',    clue: 'Grand rapace au regard perçant',        level: 3, cat: 'animaux' },
  { word: 'HIBOU',    clue: 'Rapace nocturne à aigrettes',           level: 3, cat: 'animaux' },
  { word: 'CORBEAU',  clue: 'Grand oiseau noir croassant',           level: 3, cat: 'animaux' },
  { word: 'PIGEON',   clue: 'Oiseau gris des villes',                level: 3, cat: 'animaux' },
  { word: 'SERPENT',  clue: 'Reptile qui rampe',                     level: 3, cat: 'animaux' },
  { word: 'GRENOUILLE', clue: 'Amphibien vert qui coasse',           level: 3, cat: 'animaux' },
  { word: 'ESCARGOT', clue: 'Mollusque qui porte sa maison',         level: 3, cat: 'animaux' },
  { word: 'HERISSON', clue: 'Petit mammifère couvert de piquants',   level: 3, cat: 'animaux' },
  { word: 'ECUREUIL', clue: 'Rongeur roux à queue touffue',          level: 3, cat: 'animaux' },
  { word: 'TAUREAU',  clue: 'Mâle de la vache',                      level: 3, cat: 'animaux' },
  { word: 'BEURRE',   clue: 'Matière grasse issue du lait',          level: 3, cat: 'nourriture' },
  { word: 'YAOURT',   clue: 'Laitage fermenté en pot',               level: 3, cat: 'nourriture' },
  { word: 'POULET',   clue: 'Volaille rôtie du dimanche',            level: 3, cat: 'nourriture' },
  { word: 'JAMBON',   clue: 'Charcuterie de porc',                   level: 3, cat: 'nourriture' },
  { word: 'SALADE',   clue: 'Plat de feuilles vertes assaisonnées',  level: 3, cat: 'nourriture' },
  { word: 'OIGNON',   clue: 'Légume bulbe qui fait pleurer',         level: 3, cat: 'nourriture' },
  { word: 'POIVRE',   clue: 'Épice en grains noirs, compagnon du sel', level: 3, cat: 'nourriture' },
  { word: 'FARINE',   clue: 'Poudre de blé pour faire le pain',      level: 3, cat: 'nourriture' },
  { word: 'CONFITURE', clue: 'Fruits cuits au sucre à tartiner',     level: 3, cat: 'nourriture' },
  { word: 'BISCUIT',  clue: 'Petit gâteau sec',                      level: 3, cat: 'nourriture' },
  { word: 'TARTE',    clue: 'Pâtisserie plate garnie de fruits',     level: 3, cat: 'nourriture' },
  { word: 'CREPE',    clue: 'Fine galette de la Chandeleur',         level: 3, cat: 'nourriture' },
  { word: 'SIROP',    clue: 'Liquide sucré à diluer dans l\'eau',    level: 3, cat: 'nourriture' },
  { word: 'LEGUME',   clue: 'Plante potagère comestible',            level: 3, cat: 'nourriture' },
  { word: 'FRUIT',    clue: 'Produit sucré des arbres et plantes',   level: 3, cat: 'nourriture' },
  { word: 'ORAGE',    clue: 'Tempête avec éclairs et tonnerre',      level: 3, cat: 'nature' },
  { word: 'TONNERRE', clue: 'Bruit qui suit l\'éclair',              level: 3, cat: 'nature' },
  { word: 'ECLAIR',   clue: 'Lumière brève de l\'orage, ou pâtisserie', level: 3, cat: 'nature' },
  { word: 'BROUILLARD', clue: 'Nuage au ras du sol qui réduit la visibilité', level: 3, cat: 'nature' },
  { word: 'ROSEE',    clue: 'Gouttelettes du matin sur l\'herbe',    level: 3, cat: 'nature' },
  { word: 'RACINE',   clue: 'Partie souterraine de la plante',       level: 3, cat: 'nature' },
  { word: 'FEUILLE',  clue: 'Partie verte et plate de l\'arbre',     level: 3, cat: 'nature' },
  { word: 'BRANCHE',  clue: 'Bras de l\'arbre',                      level: 3, cat: 'nature' },
  { word: 'GRAINE',   clue: 'On la sème pour faire pousser une plante', level: 3, cat: 'nature' },
  { word: 'SABLE',    clue: 'Grains fins des plages et déserts',     level: 3, cat: 'nature' },
  { word: 'VAGUE',    clue: 'Ondulation de la mer',                  level: 3, cat: 'nature' },
  { word: 'MAREE',    clue: 'Mouvement montant et descendant de la mer', level: 3, cat: 'nature' },
  { word: 'TENNIS',   clue: 'Sport de raquette sur court',           level: 3, cat: 'sport' },
  { word: 'RUGBY',    clue: 'Sport collectif au ballon ovale',       level: 3, cat: 'sport' },
  { word: 'JUDO',     clue: 'Art martial japonais en kimono',        level: 3, cat: 'sport' },
  { word: 'BOXE',     clue: 'Sport de combat avec des gants',        level: 3, cat: 'sport' },
  { word: 'DANSE',    clue: 'Art du mouvement en musique',           level: 3, cat: 'sport' },
  { word: 'ARBITRE',  clue: 'Il siffle les fautes pendant le match', level: 3, cat: 'sport' },
  { word: 'SKI',      clue: 'Glisse sur la neige',                   level: 3, cat: 'sport' },
  { word: 'CISEAUX',  clue: 'Outil à deux lames pour couper',        level: 3, cat: 'objets' },
  { word: 'MARTEAU',  clue: 'Outil pour enfoncer les clous',         level: 3, cat: 'objets' },
  { word: 'BROSSE',   clue: 'Ustensile à poils pour nettoyer ou coiffer', level: 3, cat: 'objets' },
  { word: 'PEIGNE',   clue: 'Instrument à dents pour démêler les cheveux', level: 3, cat: 'objets' },
  { word: 'SAVON',    clue: 'Il lave et fait des bulles',            level: 3, cat: 'objets' },
  { word: 'SERVIETTE', clue: 'Linge pour s\'essuyer',                level: 3, cat: 'objets' },
  { word: 'BOUTEILLE', clue: 'Récipient à goulot pour les liquides', level: 3, cat: 'objets' },
  { word: 'PANIER',   clue: 'Contenant tressé à anse',               level: 3, cat: 'objets' },
  { word: 'VALISE',   clue: 'Bagage rigide pour voyager',            level: 3, cat: 'objets' },
  { word: 'PARAPLUIE', clue: 'Il protège de la pluie',               level: 3, cat: 'objets' },
  { word: 'ECHELLE',  clue: 'On grimpe sur ses barreaux',            level: 3, cat: 'objets' },
  { word: 'CLOU',     clue: 'Tige métallique que l\'on enfonce au marteau', level: 3, cat: 'objets' },
  { word: 'FLUTE',    clue: 'Instrument à vent que l\'on souffle',   level: 3, cat: 'arts' },
  { word: 'TAMBOUR',  clue: 'Instrument à percussion à baguettes',   level: 3, cat: 'arts' },
  { word: 'DESSIN',   clue: 'Représentation au crayon',              level: 3, cat: 'arts' },
  { word: 'POEME',    clue: 'Texte en vers',                         level: 3, cat: 'arts' },
  { word: 'CONTE',    clue: 'Histoire merveilleuse pour enfants',    level: 3, cat: 'arts' },
  { word: 'ROMAN',    clue: 'Long récit de fiction en prose',        level: 3, cat: 'arts' },
  { word: 'EPAULE',   clue: 'Articulation entre le bras et le tronc', level: 3, cat: 'corps' },
  { word: 'GENOU',    clue: 'Articulation du milieu de la jambe',    level: 3, cat: 'corps' },
  { word: 'CHEVILLE', clue: 'Articulation entre la jambe et le pied', level: 3, cat: 'corps' },
  { word: 'VENTRE',   clue: 'Partie du corps qui contient l\'estomac', level: 3, cat: 'corps' },
  { word: 'VISAGE',   clue: 'Face avant de la tête',                 level: 3, cat: 'corps' },
  { word: 'FRONT',    clue: 'Partie du visage au-dessus des sourcils', level: 3, cat: 'corps' },
  { word: 'JOUE',     clue: 'Partie du visage que l\'on embrasse',   level: 3, cat: 'corps' },
  { word: 'LEVRE',    clue: 'Bord charnu de la bouche',              level: 3, cat: 'corps' },
  { word: 'COU',      clue: 'Il relie la tête au corps',             level: 3, cat: 'corps' },
  { word: 'PISCINE',  clue: 'Bassin artificiel pour nager',          level: 3, cat: 'lieux' },
  { word: 'HOPITAL',  clue: 'Établissement de soins',                level: 3, cat: 'lieux' },
  { word: 'EGLISE',   clue: 'Édifice religieux à clocher',           level: 3, cat: 'lieux' },
  { word: 'CHATEAU',  clue: 'Demeure fortifiée des rois',            level: 3, cat: 'lieux' },
  { word: 'MUSEE',    clue: 'On y expose des œuvres d\'art',         level: 3, cat: 'lieux' },
  { word: 'GARE',     clue: 'Les trains s\'y arrêtent',              level: 3, cat: 'lieux' },
  { word: 'PORT',     clue: 'Abri pour les bateaux',                 level: 3, cat: 'lieux' },
  { word: 'MAIRIE',   clue: 'Bâtiment de l\'administration communale', level: 3, cat: 'lieux' },
  { word: 'PRISON',   clue: 'On y enferme les condamnés',            level: 3, cat: 'lieux' },
  { word: 'USINE',    clue: 'Bâtiment de fabrication industrielle',  level: 3, cat: 'lieux' },
  { word: 'MOULIN',   clue: 'Il moud le grain grâce au vent ou à l\'eau', level: 3, cat: 'lieux' },
  { word: 'GROTTE',   clue: 'Cavité naturelle dans la roche',        level: 3, cat: 'lieux' },
  { word: 'CAMION',   clue: 'Gros véhicule de transport de marchandises', level: 3, cat: 'transports' },
  { word: 'METRO',    clue: 'Train souterrain des grandes villes',   level: 3, cat: 'transports' },
  { word: 'TRACTEUR', clue: 'Véhicule agricole puissant',            level: 3, cat: 'transports' },
  { word: 'FUSEE',    clue: 'Véhicule spatial à réaction',           level: 3, cat: 'transports' },

  // ─── Niveau 5-6 : Mots intermédiaires ──────────────────────────────────────
  { word: 'BIBLIOTHEQUE', clue: 'Lieu de conservation et de prêt de livres', level: 5, cat: 'lieux' },
  { word: 'PHARMACIE',    clue: 'Lieu où l\'on vend des médicaments',        level: 5, cat: 'lieux' },
  { word: 'BOULANGERIE',  clue: 'Lieu où l\'on fabrique et vend du pain',    level: 5, cat: 'lieux' },
  { word: 'SUPERMARCHE',  clue: 'Grand magasin alimentaire en libre-service', level: 5, cat: 'lieux' },
  { word: 'UNIVERSITE',   clue: 'Établissement d\'enseignement supérieur',   level: 5, cat: 'lieux' },
  { word: 'TELESCOPE',    clue: 'Instrument pour observer les astres',        level: 5, cat: 'sciences' },
  { word: 'MICROSCOPE',   clue: 'Instrument pour voir l\'infiniment petit',  level: 5, cat: 'sciences' },
  { word: 'CHIMIE',       clue: 'Science de la matière et ses transformations', level: 5, cat: 'sciences' },
  { word: 'PHYSIQUE',     clue: 'Science des lois de la nature',             level: 5, cat: 'sciences' },
  { word: 'BIOLOGIE',     clue: 'Science du vivant',                         level: 5, cat: 'sciences' },
  { word: 'GEOGRAPHIE',   clue: 'Science qui étudie la surface terrestre',   level: 5, cat: 'sciences' },
  { word: 'HISTOIRE',     clue: 'Science qui étudie le passé humain',        level: 5, cat: 'sciences' },
  { word: 'PHILOSOPHIE',  clue: 'Science de la sagesse et de la réflexion',  level: 5, cat: 'sciences' },
  { word: 'PSYCHOLOGIE',  clue: 'Science qui étudie le comportement humain', level: 5, cat: 'sciences' },
  { word: 'ECONOMIE',     clue: 'Science de la production et des échanges',  level: 5, cat: 'sciences' },
  { word: 'ELEPHANT',     clue: 'Plus grand mammifère terrestre',            level: 5, cat: 'animaux' },
  { word: 'GIRAFE',       clue: 'Animal au cou très long',                   level: 5, cat: 'animaux' },
  { word: 'TIGRE',        clue: 'Félin rayé d\'Asie',                       level: 5, cat: 'animaux' },
  { word: 'LION',         clue: 'Roi des animaux, félin africain',           level: 5, cat: 'animaux' },
  { word: 'REQUIN',       clue: 'Poisson prédateur des mers',                level: 5, cat: 'animaux' },
  { word: 'DAUPHIN',      clue: 'Mammifère marin intelligent et joueur',     level: 5, cat: 'animaux' },
  { word: 'BALEINE',      clue: 'Plus grand mammifère marin',               level: 5, cat: 'animaux' },
  { word: 'PAPILLON',     clue: 'Insecte aux ailes colorées',               level: 5, cat: 'animaux' },
  { word: 'ARAIGNEE',     clue: 'Arachnide tisseuse de toiles',             level: 5, cat: 'animaux' },
  { word: 'CROCODILE',    clue: 'Grand reptile des marais tropicaux',        level: 5, cat: 'animaux' },
  { word: 'FOOTBALL',     clue: 'Sport collectif avec un ballon rond',       level: 5, cat: 'sport' },
  { word: 'NATATION',     clue: 'Sport aquatique',                          level: 5, cat: 'sport' },
  { word: 'CYCLISME',     clue: 'Sport pratiqué sur un vélo',               level: 5, cat: 'sport' },
  { word: 'ATHLETISME',   clue: 'Ensemble des sports de course et de saut', level: 5, cat: 'sport' },
  { word: 'ESCALADE',     clue: 'Sport consistant à grimper',               level: 5, cat: 'sport' },
  { word: 'GUITARE',      clue: 'Instrument à cordes que l\'on gratte',     level: 5, cat: 'arts' },
  { word: 'VIOLON',       clue: 'Instrument à cordes et archet',            level: 5, cat: 'arts' },
  { word: 'PIANO',        clue: 'Instrument à clavier à 88 touches',        level: 5, cat: 'arts' },
  { word: 'TROMPETTE',    clue: 'Instrument à vent en cuivre',              level: 5, cat: 'arts' },
  { word: 'SCULPTURE',    clue: 'Art de créer des formes en volume',        level: 5, cat: 'arts' },
  { word: 'ARCHITECTURE', clue: 'Art de concevoir et construire des édifices', level: 5, cat: 'arts' },
  { word: 'PHOTOGRAPHIE', clue: 'Art de capturer des images par la lumière', level: 5, cat: 'arts' },
  { word: 'PRINTEMPS',    clue: 'Saison entre hiver et été',               level: 5, cat: 'temps' },
  { word: 'AUTOMNE',      clue: 'Saison entre été et hiver',               level: 5, cat: 'temps' },
  { word: 'NOEL',         clue: 'Fête du 25 décembre',                      level: 5, cat: 'fetes' },
  { word: 'PLANETE',      clue: 'Corps céleste qui tourne autour d\'une étoile', level: 5, cat: 'astronomie' },
  { word: 'SATELLITE',    clue: 'Corps qui orbite autour d\'une planète',   level: 5, cat: 'astronomie' },
  { word: 'METEORITE',    clue: 'Roche venue de l\'espace tombée sur Terre', level: 5, cat: 'astronomie' },
  { word: 'ASTRONAUTE',   clue: 'Voyageur de l\'espace',                    level: 5, cat: 'astronomie' },
  { word: 'GRAVITE',      clue: 'Force qui attire les corps vers le sol',   level: 5, cat: 'physique' },
  { word: 'ENERGIE',      clue: 'Capacité à produire un travail ou de la chaleur', level: 5, cat: 'physique' },
  { word: 'AIMANT',       clue: 'Il attire le fer',                         level: 5, cat: 'physique' },
  { word: 'BOUSSOLE',     clue: 'Instrument dont l\'aiguille indique le nord', level: 5, cat: 'sciences' },
  { word: 'THERMOMETRE',  clue: 'Instrument qui mesure la température',     level: 5, cat: 'sciences' },
  { word: 'LABORATOIRE',  clue: 'Salle d\'expériences scientifiques',       level: 5, cat: 'sciences' },
  { word: 'EXPERIENCE',   clue: 'Test scientifique pour vérifier une hypothèse', level: 5, cat: 'sciences' },
  { word: 'VACCIN',       clue: 'Injection qui protège des maladies',       level: 5, cat: 'sciences' },
  { word: 'MICROBE',      clue: 'Organisme minuscule parfois pathogène',    level: 5, cat: 'biologie' },
  { word: 'VIRUS',        clue: 'Agent infectieux microscopique',           level: 5, cat: 'biologie' },
  { word: 'CERVEAU',      clue: 'Organe de la pensée',                      level: 5, cat: 'biologie' },
  { word: 'SQUELETTE',    clue: 'Ensemble des os du corps',                 level: 5, cat: 'biologie' },
  { word: 'OXYGENE',      clue: 'Gaz indispensable à la respiration',       level: 5, cat: 'chimie' },
  { word: 'CARBONE',      clue: 'Élément chimique de base du vivant',       level: 5, cat: 'chimie' },
  { word: 'CONTINENT',    clue: 'Vaste étendue de terre : l\'Afrique en est un', level: 5, cat: 'geographie' },
  { word: 'EQUATEUR',     clue: 'Ligne imaginaire à mi-chemin des pôles',   level: 5, cat: 'geographie' },
  { word: 'TROPIQUE',     clue: 'Parallèle du Cancer ou du Capricorne',     level: 5, cat: 'geographie' },
  { word: 'GLACIER',      clue: 'Fleuve de glace en montagne',              level: 5, cat: 'geographie' },
  { word: 'CASCADE',      clue: 'Chute d\'eau naturelle',                   level: 5, cat: 'geographie' },
  { word: 'FALAISE',      clue: 'Paroi rocheuse abrupte au bord de la mer', level: 5, cat: 'geographie' },
  { word: 'PLAINE',       clue: 'Vaste étendue de terrain plat',            level: 5, cat: 'geographie' },
  { word: 'PLATEAU',      clue: 'Étendue plate en altitude',                level: 5, cat: 'geographie' },
  { word: 'DELTA',        clue: 'Embouchure d\'un fleuve en plusieurs bras', level: 5, cat: 'geographie' },
  { word: 'CANYON',       clue: 'Gorge profonde creusée par une rivière',   level: 5, cat: 'geographie' },
  { word: 'OASIS',        clue: 'Point d\'eau et de verdure dans le désert', level: 5, cat: 'geographie' },
  { word: 'SAVANE',       clue: 'Prairie tropicale aux herbes hautes',      level: 5, cat: 'geographie' },
  { word: 'JUNGLE',       clue: 'Forêt tropicale dense',                    level: 5, cat: 'geographie' },
  { word: 'PRAIRIE',      clue: 'Terrain couvert d\'herbe pour le bétail',  level: 5, cat: 'geographie' },
  { word: 'PINGOUIN',     clue: 'Oiseau marin noir et blanc de l\'Arctique', level: 5, cat: 'animaux' },
  { word: 'KANGOUROU',    clue: 'Marsupial sauteur d\'Australie',           level: 5, cat: 'animaux' },
  { word: 'PANTHERE',     clue: 'Félin tacheté ou noir',                    level: 5, cat: 'animaux' },
  { word: 'ZEBRE',        clue: 'Équidé rayé d\'Afrique',                   level: 5, cat: 'animaux' },
  { word: 'HIPPOPOTAME',  clue: 'Gros mammifère amphibie des fleuves africains', level: 5, cat: 'animaux' },
  { word: 'RHINOCEROS',   clue: 'Gros mammifère à corne sur le nez',        level: 5, cat: 'animaux' },
  { word: 'GORILLE',      clue: 'Le plus grand des singes',                 level: 5, cat: 'animaux' },
  { word: 'CHAMEAU',      clue: 'Il a deux bosses',                         level: 5, cat: 'animaux' },
  { word: 'AUTRUCHE',     clue: 'Le plus grand oiseau, il ne vole pas',     level: 5, cat: 'animaux' },
  { word: 'PERROQUET',    clue: 'Oiseau coloré qui répète les mots',        level: 5, cat: 'animaux' },
  { word: 'SCORPION',     clue: 'Arachnide au dard venimeux',               level: 5, cat: 'animaux' },
  { word: 'MEDUSE',       clue: 'Animal marin gélatineux et urticant',      level: 5, cat: 'animaux' },
  { word: 'PIEUVRE',      clue: 'Mollusque marin à huit bras',              level: 5, cat: 'animaux' },
  { word: 'HOMARD',       clue: 'Crustacé marin aux grosses pinces',        level: 5, cat: 'animaux' },
  { word: 'FLAMANT',      clue: 'Grand oiseau rose des lagunes',            level: 5, cat: 'animaux' },
  { word: 'ARCHITECTE',   clue: 'Il conçoit les bâtiments',                 level: 5, cat: 'metiers' },
  { word: 'INGENIEUR',    clue: 'Il conçoit des solutions techniques',      level: 5, cat: 'metiers' },
  { word: 'JOURNALISTE',  clue: 'Il informe le public',                     level: 5, cat: 'metiers' },
  { word: 'VETERINAIRE',  clue: 'Médecin des animaux',                      level: 5, cat: 'metiers' },
  { word: 'PHARMACIEN',   clue: 'Il délivre les médicaments',               level: 5, cat: 'metiers' },
  { word: 'ELECTRICIEN',  clue: 'Il installe les circuits électriques',     level: 5, cat: 'metiers' },
  { word: 'PLOMBIER',     clue: 'Il répare les canalisations',              level: 5, cat: 'metiers' },
  { word: 'MENUISIER',    clue: 'Artisan qui travaille le bois',            level: 5, cat: 'metiers' },
  { word: 'COMPTABLE',    clue: 'Il tient les comptes de l\'entreprise',    level: 5, cat: 'metiers' },
  { word: 'TRADUCTEUR',   clue: 'Il fait passer un texte d\'une langue à une autre', level: 5, cat: 'metiers' },
  { word: 'ORCHESTRE',    clue: 'Grand ensemble de musiciens',              level: 5, cat: 'arts' },
  { word: 'OPERA',        clue: 'Théâtre lyrique chanté',                   level: 5, cat: 'arts' },
  { word: 'BALLET',       clue: 'Spectacle de danse classique',             level: 5, cat: 'arts' },
  { word: 'PORTRAIT',     clue: 'Représentation d\'une personne',           level: 5, cat: 'arts' },
  { word: 'AQUARELLE',    clue: 'Peinture à l\'eau aux couleurs transparentes', level: 5, cat: 'arts' },
  { word: 'MOSAIQUE',     clue: 'Assemblage décoratif de petits carreaux',  level: 5, cat: 'arts' },
  { word: 'POESIE',       clue: 'Art d\'écrire en vers',                    level: 5, cat: 'arts' },
  { word: 'COMEDIE',      clue: 'Pièce de théâtre qui fait rire',           level: 5, cat: 'arts' },
  { word: 'TRAGEDIE',     clue: 'Pièce de théâtre au dénouement funeste',   level: 5, cat: 'arts' },
  { word: 'SYMPHONIE',    clue: 'Grande œuvre pour orchestre',              level: 5, cat: 'arts' },
  { word: 'CHORALE',      clue: 'Groupe de chanteurs',                      level: 5, cat: 'arts' },
  { word: 'ACCORDEON',    clue: 'Instrument à soufflet des bals musette',   level: 5, cat: 'arts' },
  { word: 'SAXOPHONE',    clue: 'Instrument à vent roi du jazz',            level: 5, cat: 'arts' },
  { word: 'CLARINETTE',   clue: 'Instrument à vent en bois à anche',        level: 5, cat: 'arts' },
  { word: 'VIOLONCELLE',  clue: 'Grand instrument à cordes joué assis',     level: 5, cat: 'arts' },
  { word: 'HARPE',        clue: 'Grand instrument à cordes pincées',        level: 5, cat: 'arts' },
  { word: 'AUBERGINE',    clue: 'Légume violet allongé',                    level: 5, cat: 'nourriture' },
  { word: 'COURGETTE',    clue: 'Légume vert allongé de la ratatouille',    level: 5, cat: 'nourriture' },
  { word: 'EPINARD',      clue: 'Légume feuille préféré de Popeye',         level: 5, cat: 'nourriture' },
  { word: 'ARTICHAUT',    clue: 'Légume dont on mange le cœur et les feuilles', level: 5, cat: 'nourriture' },
  { word: 'ASPERGE',      clue: 'Légume printanier en tige blanche ou verte', level: 5, cat: 'nourriture' },
  { word: 'BROCOLI',      clue: 'Chou vert en petits bouquets',             level: 5, cat: 'nourriture' },
  { word: 'ANANAS',       clue: 'Fruit tropical à écorce écailleuse',       level: 5, cat: 'nourriture' },
  { word: 'ABRICOT',      clue: 'Fruit orangé à noyau de l\'été',           level: 5, cat: 'nourriture' },
  { word: 'FRAMBOISE',    clue: 'Petit fruit rouge des ronces',             level: 5, cat: 'nourriture' },
  { word: 'MYRTILLE',     clue: 'Petite baie bleue des montagnes',          level: 5, cat: 'nourriture' },
  { word: 'NOISETTE',     clue: 'Petit fruit sec du noisetier',             level: 5, cat: 'nourriture' },
  { word: 'AMANDE',       clue: 'Fruit sec ovale à coque, base du massepain', level: 5, cat: 'nourriture' },
  { word: 'PISTACHE',     clue: 'Petite graine verte à coque',              level: 5, cat: 'nourriture' },
  { word: 'CANNELLE',     clue: 'Épice en bâtonnets bruns',                 level: 5, cat: 'nourriture' },
  { word: 'VANILLE',      clue: 'Gousse parfumée des desserts',             level: 5, cat: 'nourriture' },
  { word: 'MOUTARDE',     clue: 'Condiment jaune piquant de Dijon',         level: 5, cat: 'nourriture' },
  { word: 'VINAIGRE',     clue: 'Condiment acide de la vinaigrette',        level: 5, cat: 'nourriture' },
  { word: 'OMELETTE',     clue: 'Plat d\'œufs battus cuits à la poêle',     level: 5, cat: 'nourriture' },
  { word: 'QUICHE',       clue: 'Tarte salée lorraine aux lardons',         level: 5, cat: 'nourriture' },
  { word: 'RATATOUILLE',  clue: 'Plat provençal de légumes mijotés',        level: 5, cat: 'nourriture' },
  { word: 'CROISSANT',    clue: 'Viennoiserie feuilletée du petit-déjeuner', level: 5, cat: 'nourriture' },
  { word: 'BAGUETTE',     clue: 'Pain français long et croustillant',       level: 5, cat: 'nourriture' },
  { word: 'BASKETBALL',   clue: 'Sport où l\'on marque des paniers',        level: 5, cat: 'sport' },
  { word: 'VOLLEYBALL',   clue: 'Sport collectif au filet, sans contact',   level: 5, cat: 'sport' },
  { word: 'HANDBALL',     clue: 'Sport collectif où l\'on marque à la main', level: 5, cat: 'sport' },
  { word: 'GYMNASTIQUE',  clue: 'Sport d\'agrès et de souplesse',           level: 5, cat: 'sport' },
  { word: 'MARATHON',     clue: 'Course à pied de 42,195 km',               level: 5, cat: 'sport' },
  { word: 'ESCRIME',      clue: 'Sport de combat à l\'épée ou au fleuret',  level: 5, cat: 'sport' },
  { word: 'AVIRON',       clue: 'Sport de rame en équipe',                  level: 5, cat: 'sport' },
  { word: 'PLONGEE',      clue: 'Exploration sous-marine avec bouteilles',  level: 5, cat: 'sport' },
  { word: 'PATINAGE',     clue: 'Glisse sur la glace, artistique ou de vitesse', level: 5, cat: 'sport' },
  { word: 'PETANQUE',     clue: 'Jeu de boules provençal',                  level: 5, cat: 'sport' },
  { word: 'BADMINTON',    clue: 'Sport de raquette au volant',              level: 5, cat: 'sport' },
  { word: 'TEMPETE',      clue: 'Vent violent accompagné de pluie',         level: 5, cat: 'nature' },
  { word: 'OURAGAN',      clue: 'Cyclone tropical dévastateur',             level: 5, cat: 'nature' },
  { word: 'CANICULE',     clue: 'Période de chaleur extrême',               level: 5, cat: 'nature' },
  { word: 'SECHERESSE',   clue: 'Longue période sans pluie',                level: 5, cat: 'nature' },
  { word: 'AVALANCHE',    clue: 'Masse de neige qui dévale la pente',       level: 5, cat: 'nature' },
  { word: 'INONDATION',   clue: 'Débordement des eaux sur les terres',      level: 5, cat: 'nature' },
  { word: 'CREPUSCULE',   clue: 'Lumière déclinante après le coucher du soleil', level: 5, cat: 'temps' },
  { word: 'AURORE',       clue: 'Première lueur du jour',                   level: 5, cat: 'temps' },
  { word: 'HORIZON',      clue: 'Ligne où le ciel semble toucher la terre', level: 5, cat: 'nature' },
  { word: 'ATMOSPHERE',   clue: 'Couche de gaz qui entoure la Terre',       level: 5, cat: 'nature' },

  // ─── Niveau 7-8 : Mots avancés ─────────────────────────────────────────────
  { word: 'ARCHIPEL',     clue: 'Ensemble d\'îles dans une mer',           level: 7, cat: 'geographie' },
  { word: 'PENINSULE',    clue: 'Grande avancée de terre dans la mer',     level: 7, cat: 'geographie' },
  { word: 'FJORD',        clue: 'Bras de mer encaissé d\'origine glaciaire', level: 7, cat: 'geographie' },
  { word: 'VOLCAN',       clue: 'Montagne crachant du feu et de la lave',  level: 7, cat: 'geographie' },
  { word: 'SEISME',       clue: 'Tremblement de terre',                    level: 7, cat: 'geographie' },
  { word: 'TSUNAMI',      clue: 'Vague géante causée par un séisme',       level: 7, cat: 'geographie' },
  { word: 'ECLIPSE',      clue: 'Occultation d\'un astre par un autre',    level: 7, cat: 'astronomie' },
  { word: 'COMETE',       clue: 'Corps céleste à longue traîne lumineuse', level: 7, cat: 'astronomie' },
  { word: 'GALAXIE',      clue: 'Système de milliards d\'étoiles',         level: 7, cat: 'astronomie' },
  { word: 'NEBULEUSE',    clue: 'Nuage de gaz et poussières interstellaires', level: 7, cat: 'astronomie' },
  { word: 'PHOTON',       clue: 'Particule élémentaire de lumière',        level: 7, cat: 'physique' },
  { word: 'ELECTRON',     clue: 'Particule chargée négativement',          level: 7, cat: 'physique' },
  { word: 'PROTON',       clue: 'Particule du noyau atomique chargée +',   level: 7, cat: 'physique' },
  { word: 'ATOME',        clue: 'Plus petite unité d\'un élément chimique', level: 7, cat: 'physique' },
  { word: 'MOLECULE',     clue: 'Ensemble d\'atomes liés chimiquement',    level: 7, cat: 'physique' },
  { word: 'SYMBIOSE',     clue: 'Association bénéfique de deux espèces',   level: 7, cat: 'biologie' },
  { word: 'CHLOROPHYLLE', clue: 'Pigment vert des plantes',                level: 7, cat: 'biologie' },
  { word: 'CHROMOSOME',   clue: 'Structure portant l\'ADN dans la cellule', level: 7, cat: 'biologie' },
  { word: 'MEMBRANE',     clue: 'Fine couche qui entoure une cellule',     level: 7, cat: 'biologie' },
  { word: 'EVAPORATION',  clue: 'Passage de l\'état liquide à gazeux',     level: 7, cat: 'physique' },
  { word: 'CONDENSATION', clue: 'Passage de l\'état gazeux à liquide',     level: 7, cat: 'physique' },
  { word: 'COMBUSTION',   clue: 'Réaction chimique produisant chaleur et lumière', level: 7, cat: 'chimie' },
  { word: 'CATALYSE',     clue: 'Accélération d\'une réaction par un tiers', level: 7, cat: 'chimie' },
  { word: 'OXYDATION',    clue: 'Réaction avec l\'oxygène, cause la rouille', level: 7, cat: 'chimie' },
  { word: 'PALINDROME',   clue: 'Mot se lisant identiquement dans les deux sens', level: 7, cat: 'langue' },
  { word: 'SYNONYME',     clue: 'Mot de sens identique à un autre',        level: 7, cat: 'langue' },
  { word: 'ANTONYME',     clue: 'Mot de sens contraire à un autre',        level: 7, cat: 'langue' },
  { word: 'METAPHORE',    clue: 'Figure de style par comparaison implicite', level: 7, cat: 'langue' },
  { word: 'OXYMORE',      clue: 'Alliance de termes contradictoires',       level: 7, cat: 'langue' },
  { word: 'ISTHME',       clue: 'Étroite bande de terre entre deux mers',  level: 7, cat: 'geographie' },
  { word: 'ATOLL',        clue: 'Île corallienne en anneau autour d\'un lagon', level: 7, cat: 'geographie' },
  { word: 'GEYSER',       clue: 'Source jaillissante d\'eau chaude',       level: 7, cat: 'geographie' },
  { word: 'BANQUISE',     clue: 'Couche de glace flottant sur la mer polaire', level: 7, cat: 'geographie' },
  { word: 'STALACTITE',   clue: 'Concrétion calcaire qui descend du plafond', level: 7, cat: 'geographie' },
  { word: 'STALAGMITE',   clue: 'Concrétion calcaire qui monte du sol',    level: 7, cat: 'geographie' },
  { word: 'MERIDIEN',     clue: 'Ligne imaginaire reliant les deux pôles', level: 7, cat: 'geographie' },
  { word: 'LATITUDE',     clue: 'Position angulaire nord-sud sur le globe', level: 7, cat: 'geographie' },
  { word: 'LONGITUDE',    clue: 'Position angulaire est-ouest sur le globe', level: 7, cat: 'geographie' },
  { word: 'ALTITUDE',     clue: 'Hauteur par rapport au niveau de la mer', level: 7, cat: 'geographie' },
  { word: 'NEUTRON',      clue: 'Particule du noyau sans charge électrique', level: 7, cat: 'physique' },
  { word: 'ISOTOPE',      clue: 'Variante d\'un élément au nombre de neutrons différent', level: 7, cat: 'chimie' },
  { word: 'ENZYME',       clue: 'Protéine qui accélère les réactions biologiques', level: 7, cat: 'biologie' },
  { word: 'BACTERIE',     clue: 'Micro-organisme unicellulaire sans noyau', level: 7, cat: 'biologie' },
  { word: 'NEURONE',      clue: 'Cellule nerveuse du cerveau',             level: 7, cat: 'biologie' },
  { word: 'GENETIQUE',    clue: 'Science de l\'hérédité',                  level: 7, cat: 'biologie' },
  { word: 'MUTATION',     clue: 'Modification aléatoire de l\'ADN',        level: 7, cat: 'biologie' },
  { word: 'PHOTOSYNTHESE', clue: 'Fabrication de sucre par les plantes grâce à la lumière', level: 7, cat: 'biologie' },
  { word: 'ECOSYSTEME',   clue: 'Milieu naturel et les espèces qui y vivent', level: 7, cat: 'biologie' },
  { word: 'FREQUENCE',    clue: 'Nombre d\'oscillations par seconde',      level: 7, cat: 'physique' },
  { word: 'AMPLITUDE',    clue: 'Hauteur maximale d\'une oscillation',     level: 7, cat: 'physique' },
  { word: 'INERTIE',      clue: 'Résistance d\'un corps au changement de mouvement', level: 7, cat: 'physique' },
  { word: 'PESANTEUR',    clue: 'Force de gravité à la surface de la Terre', level: 7, cat: 'physique' },
  { word: 'HOMONYME',     clue: 'Mot qui se prononce comme un autre',      level: 7, cat: 'langue' },
  { word: 'ANAGRAMME',    clue: 'Mot formé des lettres d\'un autre mot',   level: 7, cat: 'langue' },
  { word: 'ETYMOLOGIE',   clue: 'Étude de l\'origine des mots',            level: 7, cat: 'langue' },
  { word: 'ALLITERATION', clue: 'Répétition d\'une consonne dans une phrase', level: 7, cat: 'langue' },
  { word: 'HYPERBOLE',    clue: 'Figure de style par exagération',         level: 7, cat: 'langue' },
  { word: 'EUPHEMISME',   clue: 'Figure de style qui adoucit une réalité', level: 7, cat: 'langue' },
  { word: 'PERIPHRASE',   clue: 'Expression qui remplace un mot unique',   level: 7, cat: 'langue' },
  { word: 'DYNASTIE',     clue: 'Succession de souverains d\'une même famille', level: 7, cat: 'histoire' },
  { word: 'ARMISTICE',    clue: 'Accord qui suspend les combats',          level: 7, cat: 'histoire' },
  { word: 'RENAISSANCE',  clue: 'Période artistique des XVe et XVIe siècles', level: 7, cat: 'histoire' },
  { word: 'ARCHEOLOGIE',  clue: 'Étude des civilisations par leurs vestiges', level: 7, cat: 'histoire' },
  { word: 'HIEROGLYPHE',  clue: 'Signe de l\'écriture égyptienne antique', level: 7, cat: 'histoire' },
  { word: 'PARCHEMIN',    clue: 'Peau préparée servant de support d\'écriture', level: 7, cat: 'histoire' },
  { word: 'NOTAIRE',      clue: 'Officier public qui authentifie les actes', level: 7, cat: 'metiers' },
  { word: 'CHIRURGIEN',   clue: 'Médecin qui opère',                       level: 7, cat: 'metiers' },
  { word: 'GEOLOGUE',     clue: 'Scientifique qui étudie les roches',      level: 7, cat: 'metiers' },
  { word: 'SOMMELIER',    clue: 'Expert des vins au restaurant',           level: 7, cat: 'metiers' },
  { word: 'HORLOGER',     clue: 'Artisan des montres et pendules',         level: 7, cat: 'metiers' },
  { word: 'EBENISTE',     clue: 'Artisan des meubles en bois précieux',    level: 7, cat: 'metiers' },
  { word: 'FORGERON',     clue: 'Artisan qui travaille le métal à la forge', level: 7, cat: 'metiers' },
  { word: 'APICULTEUR',   clue: 'Éleveur d\'abeilles',                     level: 7, cat: 'metiers' },
  { word: 'VIGNERON',     clue: 'Il cultive la vigne et fait le vin',      level: 7, cat: 'metiers' },
  { word: 'CARTOGRAPHE',  clue: 'Il dessine les cartes',                   level: 7, cat: 'metiers' },

  // ─── Niveau 9-10 : Mots experts ────────────────────────────────────────────
  { word: 'BIOLUMINESCENCE', clue: 'Émission de lumière par des organismes vivants', level: 9, cat: 'biologie' },
  { word: 'TAUTOLOGIE',      clue: 'Répétition inutile d\'une même idée',            level: 9, cat: 'langue' },
  { word: 'PLEONASME',       clue: 'Répétition d\'une idée déjà exprimée',           level: 9, cat: 'langue' },
  { word: 'ANACHRONISME',    clue: 'Erreur plaçant un fait dans une époque erronée', level: 9, cat: 'histoire' },
  { word: 'ESCHATOLOGIE',    clue: 'Doctrine des fins dernières de l\'humanité',     level: 9, cat: 'philosophie' },
  { word: 'EPISTEMOLOGIE',   clue: 'Philosophie de la connaissance scientifique',    level: 9, cat: 'philosophie' },
  { word: 'HERMENEUTIQUE',   clue: 'Science de l\'interprétation des textes',       level: 9, cat: 'philosophie' },
  { word: 'DIALECTIQUE',     clue: 'Méthode de raisonnement par thèse et antithèse', level: 9, cat: 'philosophie' },
  { word: 'PHENOMENOLOGIE',  clue: 'Étude des phénomènes de la conscience',         level: 9, cat: 'philosophie' },
  { word: 'THERMODYNAMIQUE', clue: 'Science de la chaleur et de l\'énergie',        level: 9, cat: 'physique' },
  { word: 'HYDRODYNAMIQUE',  clue: 'Étude des fluides en mouvement',                level: 9, cat: 'physique' },
  { word: 'MAGNETISME',      clue: 'Propriété physique des aimants',                level: 9, cat: 'physique' },
  { word: 'QUASAR',          clue: 'Noyau galactique actif très lumineux',          level: 9, cat: 'astronomie' },
  { word: 'PULSAR',          clue: 'Étoile à neutrons émettant des pulsations',     level: 9, cat: 'astronomie' },
  { word: 'SUPERNOVA',       clue: 'Explosion cataclysmique d\'une étoile mourante', level: 9, cat: 'astronomie' },
  { word: 'ANTIMATIERE',     clue: 'Matière dont les particules ont charges opposées', level: 9, cat: 'physique' },
  { word: 'XENOPHOBE',       clue: 'Qui a peur ou méprise les étrangers',           level: 9, cat: 'sociologie' },
  { word: 'PHILANTHROPE',    clue: 'Personne qui aime l\'humanité et la soutient',  level: 9, cat: 'sociologie' },
  { word: 'ONOMATOPEE',      clue: 'Mot qui imite un son : boum, crac',             level: 9, cat: 'langue' },
  { word: 'PALEONTOLOGIE',   clue: 'Science des fossiles',                          level: 9, cat: 'sciences' },
  { word: 'ENTOMOLOGIE',     clue: 'Science qui étudie les insectes',               level: 9, cat: 'sciences' },
  { word: 'ORNITHOLOGIE',    clue: 'Science qui étudie les oiseaux',                level: 9, cat: 'sciences' },
  { word: 'SYLLOGISME',      clue: 'Raisonnement en deux prémisses et une conclusion', level: 9, cat: 'philosophie' },
  { word: 'SOPHISME',        clue: 'Raisonnement faux à l\'apparence logique',      level: 9, cat: 'philosophie' },
  { word: 'PARADIGME',       clue: 'Modèle de pensée dominant',                     level: 9, cat: 'philosophie' },
  { word: 'HEURISTIQUE',     clue: 'Méthode de découverte par approximation',       level: 9, cat: 'philosophie' },
  { word: 'SERENDIPITE',     clue: 'Découverte heureuse faite par hasard',          level: 9, cat: 'sciences' },
  { word: 'IDIOSYNCRASIE',   clue: 'Manière d\'être propre à un individu',          level: 9, cat: 'langue' },
  { word: 'SYNECDOQUE',      clue: 'Figure de style qui prend la partie pour le tout', level: 9, cat: 'langue' },
  { word: 'APHORISME',       clue: 'Formule brève qui résume une pensée',           level: 9, cat: 'langue' },
  { word: 'PALIMPSESTE',     clue: 'Manuscrit gratté puis réécrit',                 level: 9, cat: 'histoire' },
  { word: 'QUINTESSENCE',    clue: 'Ce qu\'il y a de plus pur et d\'essentiel',     level: 9, cat: 'philosophie' },
  { word: 'OBSOLESCENCE',    clue: 'Vieillissement programmé ou naturel d\'un produit', level: 9, cat: 'sociologie' },
  { word: 'NUMISMATIQUE',    clue: 'Étude des monnaies et médailles',               level: 9, cat: 'histoire' },
  { word: 'EPHEMERIDE',      clue: 'Table des positions des astres jour par jour',  level: 9, cat: 'astronomie' },
];

/**
 * Thèmes proposés dans l'interface. Chaque thème regroupe une ou plusieurs
 * catégories de la banque de mots. `cats: null` = toutes les catégories.
 */
export const THEMES = [
  { id: 'tous',       label: 'Tous les thèmes',  cats: null },
  { id: 'animaux',    label: 'Animaux',          cats: ['animaux'] },
  { id: 'geographie', label: 'Géographie',       cats: ['geographie', 'lieux'] },
  { id: 'sciences',   label: 'Sciences',         cats: ['sciences', 'astronomie', 'physique', 'biologie', 'chimie'] },
  { id: 'nature',     label: 'Nature & météo',   cats: ['nature', 'temps'] },
  { id: 'nourriture', label: 'Nourriture',       cats: ['nourriture'] },
  { id: 'sport',      label: 'Sports & loisirs', cats: ['sport', 'loisirs'] },
  { id: 'arts',       label: 'Arts & lettres',   cats: ['arts', 'langue', 'histoire', 'philosophie'] },
  { id: 'metiers',    label: 'Métiers',          cats: ['metiers'] },
];

/**
 * Retourne les mots compatibles avec un niveau de difficulté donné.
 * La plage s'élargit légèrement pour avoir suffisamment de mots.
 * @param {number} difficulty - Niveau 1 à 10
 * @param {number} count - Nombre de mots souhaités
 * @param {string} [theme='tous'] - Identifiant de thème (voir THEMES)
 */
export function getWordsForDifficulty(difficulty, count, theme = 'tous') {
  // Définir la plage de niveaux selon la difficulté
  let minLevel, maxLevel;
  if (difficulty <= 2) {
    minLevel = 1; maxLevel = 2;
  } else if (difficulty <= 4) {
    minLevel = 1; maxLevel = 4;
  } else if (difficulty <= 6) {
    minLevel = 3; maxLevel = 6;
  } else if (difficulty <= 8) {
    minLevel = 5; maxLevel = 8;
  } else {
    minLevel = 7; maxLevel = 10;
  }

  // Filtre de thème
  const themeDef = THEMES.find((t) => t.id === theme);
  const cats = themeDef ? themeDef.cats : null;
  const inTheme = (w) => cats === null || cats.includes(w.cat);

  // Filtrer par thème et par niveau
  let pool = WORD_BANK.filter(
    (w) => inTheme(w) && w.level >= minLevel && w.level <= maxLevel && w.word.length >= 3
  );

  // Si le thème ne fournit pas assez de mots dans la plage de niveaux,
  // élargir à tous les niveaux du thème plutôt que de renvoyer une grille vide.
  if (pool.length < count) {
    pool = WORD_BANK.filter((w) => inTheme(w) && w.word.length >= 3);
  }

  // Mélanger aléatoirement (Fisher-Yates)
  const shuffled = [...pool];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }

  return shuffled.slice(0, Math.min(count, shuffled.length));
}

/**
 * Taille de grille recommandée selon la difficulté.
 */
export function getGridSize(difficulty) {
  if (difficulty <= 2) return 10;
  if (difficulty <= 4) return 11;
  if (difficulty <= 6) return 13;
  if (difficulty <= 8) return 15;
  return 15;
}

/**
 * Nombre de mots cibles selon la difficulté.
 */
export function getWordCount(difficulty) {
  if (difficulty <= 2) return 8;
  if (difficulty <= 4) return 11;
  if (difficulty <= 6) return 14;
  if (difficulty <= 8) return 18;
  return 22;
}
